## Iteración en Pandas Dataframe

### Adrián Vázquez

#### 21/06/21

<b> Iterando con .iterrows() </b>

- Devuelve cada fila del Dataframe como una tuple de pares (indice, serie pandas )

In [2]:
import pandas as pd 
import numpy as np

In [3]:
pit_df = pd.read_csv('https://assets.datacamp.com/production/repositories/3581/datasets/779033fb8fb5021aee9ff46253980abcbc5851f3/baseball_stats.csv')

In [4]:
print(display(pit_df))

,Team,League,Year,RS,RA,W,OBP,SLG,BA,Playoffs,RankSeason,RankPlayoffs,G,OOBP,OSLG
0,ARI,NL,2012,734,688,81,0.328,0.418,0.259,0,NaN,NaN,162,0.317,0.415
1,ATL,NL,2012,700,600,94,0.320,0.389,0.247,1,4.0,5.0,162,0.306,0.378
2,BAL,AL,2012,712,705,93,0.311,0.417,0.247,1,5.0,4.0,162,0.315,0.403
3,BOS,AL,2012,734,806,69,0.315,0.415,0.260,0,NaN,NaN,162,0.331,0.428
4,CHC,NL,2012,613,759,61,0.302,0.378,0.240,0,NaN,NaN,162,0.335,0.424
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1227,PHI,NL,1962,705,759,81,0.330,0.390,0.260,0,NaN,NaN,161,NaN,NaN
1228,PIT,NL,1962,706,626,93,0.321,0.394,0.268,0,NaN,NaN,161,NaN,NaN
1229,SFG,NL,1962,878,690,103,0.341,0.441,0.278,1,1.0,2.0,165,NaN,NaN
1230,STL,NL,1962,774,664,84,0.335,0.394,0.271,0,NaN,NaN,163,NaN,NaN
1231,WSA,AL,1962,599,716,60,0.308,0.373,0.250,0,NaN,NaN,162,NaN,NaN

None

<b> Utilizando .iterrows() </b>

In [18]:
for i, row in pit_df.iterrows():
    print(row)
    print('\n')

Team              ARI
League             NL
Year             2012
RS                734
RA                688
W                  81
OBP             0.328
SLG             0.418
BA              0.259
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.317
OSLG            0.415
Name: 0, dtype: object


Team              ATL
League             NL
Year             2012
RS                700
RA                600
W                  94
OBP              0.32
SLG             0.389
BA              0.247
Playoffs            1
RankSeason          4
RankPlayoffs        5
G                 162
OOBP            0.306
OSLG            0.378
Name: 1, dtype: object


Team              BAL
League             AL
Year             2012
RS                712
RA                705
W                  93
OBP             0.311
SLG             0.417
BA              0.247
Playoffs            1
RankSeason          5
RankPlayoffs        4
G                 162
OOBP            0.315
OSLG            0.403
Name: 2, dtype: object


Team              BOS
League             AL
Year             2012
RS                734
RA                806
W                  69
OBP             0.315
SLG             0.415
BA               0.26
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.331
OSLG            0.428
Name: 3, dtype: object


Team              CHC
League             NL
Year             2012
RS                613
RA                759
W                  61
OBP             0.302
SLG             0.378
BA               0.24
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.335
OSLG            0.424
Name: 4, dtype: object


Team              CHW
League             AL
Year             2012
RS                748
RA                676
W                  85
OBP             0.318
SLG             0.422
BA              0.255
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.319
OSLG            0.405
Name: 5, dtype: object


Team              CIN
League             NL
Year             2012
RS                669
RA                588
W                  97
OBP             0.315
SLG             0.411
BA              0.251
Playoffs            1
RankSeason          2
RankPlayoffs        4
G                 162
OOBP            0.305
OSLG             0.39
Name: 6, dtype: object


Team              CLE
League             AL
Year             2012
RS                667
RA                845
W                  68
OBP             0.324
SLG             0.381
BA              0.251
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.336
OSLG             0.43
Name: 7, dtype: object


Team              COL
League             NL
Year             2012
RS                758
RA                890
W                  64
OBP              0.33
SLG             0.436
BA              0.274
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.357
OSLG             0.47
Name: 8, dtype: object


Team              DET
League             AL
Year             2012
RS                726
RA                670
W                  88
OBP             0.335
SLG             0.422
BA              0.268
Playoffs            1
RankSeason          6
RankPlayoffs        2
G                 162
OOBP            0.314
OSLG            0.402
Name: 9, dtype: object


Team              HOU
League             NL
Year             2012
RS                583
RA                794
W                  55
OBP             0.302
SLG             0.371
BA              0.236
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.337
OSLG            0.427
Name: 10, dtype: object


Team              KCR
League             AL
Year             2012
RS                676
RA                746
W                  72
OBP             0.317
SLG               0.4
BA              0.265
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.339
OSLG            0.423
Name: 11, dtype: object


Team              LAA
League             AL
Year             2012
RS                767
RA                699
W                  89
OBP             0.332
SLG             0.433
BA              0.274
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP             0.31
OSLG            0.403
Name: 12, dtype: object


Team              LAD
League             NL
Year             2012
RS                637
RA                597
W                  86
OBP             0.317
SLG             0.374
BA              0.252
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP             0.31
OSLG            0.364
Name: 13, dtype: object


Team              MIA
League             NL
Year             2012
RS                609
RA                724
W                  69
OBP             0.308
SLG             0.382
BA              0.244
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.327
OSLG            0.399
Name: 14, dtype: object


Team              MIL
League             NL
Year             2012
RS                776
RA                733
W                  83
OBP             0.325
SLG             0.437
BA              0.259
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.326
OSLG            0.414
Name: 15, dtype: object


Team              MIN
League             AL
Year             2012
RS                701
RA                832
W                  66
OBP             0.325
SLG              0.39
BA               0.26
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.333
OSLG            0.442
Name: 16, dtype: object


Team              NYM
League             NL
Year             2012
RS                650
RA                709
W                  74
OBP             0.316
SLG             0.386
BA              0.249
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.315
OSLG            0.401
Name: 17, dtype: object


Team              NYY
League             AL
Year             2012
RS                804
RA                668
W                  95
OBP             0.337
SLG             0.453
BA              0.265
Playoffs            1
RankSeason          3
RankPlayoffs        3
G                 162
OOBP            0.311
OSLG            0.419
Name: 18, dtype: object


Team              OAK
League             AL
Year             2012
RS                713
RA                614
W                  94
OBP              0.31
SLG             0.404
BA              0.238
Playoffs            1
RankSeason          4
RankPlayoffs        4
G                 162
OOBP            0.306
OSLG            0.378
Name: 19, dtype: object


Team              PHI
League             NL
Year             2012
RS                684
RA                680
W                  81
OBP             0.317
SLG               0.4
BA              0.255
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.306
OSLG            0.407
Name: 20, dtype: object


Team              PIT
League             NL
Year             2012
RS                651
RA                674
W                  79
OBP             0.304
SLG             0.395
BA              0.243
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.314
OSLG             0.39
Name: 21, dtype: object


Team              SDP
League             NL
Year             2012
RS                651
RA                710
W                  76
OBP             0.319
SLG              0.38
BA              0.247
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.319
OSLG            0.398
Name: 22, dtype: object


Team              SEA
League             AL
Year             2012
RS                619
RA                651
W                  75
OBP             0.296
SLG             0.369
BA              0.234
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.308
OSLG            0.394
Name: 23, dtype: object


Team              SFG
League             NL
Year             2012
RS                718
RA                649
W                  94
OBP             0.327
SLG             0.397
BA              0.269
Playoffs            1
RankSeason          4
RankPlayoffs        1
G                 162
OOBP            0.313
OSLG            0.393
Name: 24, dtype: object


Team              STL
League             NL
Year             2012
RS                765
RA                648
W                  88
OBP             0.338
SLG             0.421
BA              0.271
Playoffs            1
RankSeason          6
RankPlayoffs        3
G                 162
OOBP            0.313
OSLG            0.387
Name: 25, dtype: object


Team              TBR
League             AL
Year             2012
RS                697
RA                577
W                  90
OBP             0.317
SLG             0.394
BA               0.24
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.294
OSLG            0.352
Name: 26, dtype: object


Team              TEX
League             AL
Year             2012
RS                808
RA                707
W                  93
OBP             0.334
SLG             0.446
BA              0.273
Playoffs            1
RankSeason          5
RankPlayoffs        5
G                 162
OOBP            0.309
OSLG            0.408
Name: 27, dtype: object


Team              TOR
League             AL
Year             2012
RS                716
RA                784
W                  73
OBP             0.309
SLG             0.407
BA              0.245
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.335
OSLG            0.438
Name: 28, dtype: object


Team              WSN
League             NL
Year             2012
RS                731
RA                594
W                  98
OBP             0.322
SLG             0.428
BA              0.261
Playoffs            1
RankSeason          1
RankPlayoffs        4
G                 162
OOBP            0.303
OSLG            0.373
Name: 29, dtype: object


Team              ARI
League             NL
Year             2011
RS                731
RA                662
W                  94
OBP             0.322
SLG             0.413
BA               0.25
Playoffs            1
RankSeason          5
RankPlayoffs        4
G                 162
OOBP            0.316
OSLG            0.409
Name: 30, dtype: object


Team              ATL
League             NL
Year             2011
RS                641
RA                605
W                  89
OBP             0.308
SLG             0.387
BA              0.243
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP             0.31
OSLG            0.361
Name: 31, dtype: object


Team              BAL
League             AL
Year             2011
RS                708
RA                860
W                  69
OBP             0.316
SLG             0.413
BA              0.257
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.341
OSLG             0.46
Name: 32, dtype: object


Team              BOS
League             AL
Year             2011
RS                875
RA                737
W                  90
OBP             0.349
SLG             0.461
BA               0.28
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.322
OSLG            0.392
Name: 33, dtype: object


Team              CHC
League             NL
Year             2011
RS                654
RA                756
W                  71
OBP             0.314
SLG             0.401
BA              0.256
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.335
OSLG            0.413
Name: 34, dtype: object


Team              CHW
League             AL
Year             2011
RS                654
RA                706
W                  79
OBP             0.319
SLG             0.388
BA              0.252
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.317
OSLG            0.397
Name: 35, dtype: object


Team              CIN
League             NL
Year             2011
RS                735
RA                720
W                  79
OBP             0.326
SLG             0.408
BA              0.256
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.325
OSLG            0.415
Name: 36, dtype: object


Team              CLE
League             AL
Year             2011
RS                704
RA                760
W                  80
OBP             0.317
SLG             0.396
BA               0.25
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.323
OSLG            0.413
Name: 37, dtype: object


Team              COL
League             NL
Year             2011
RS                735
RA                774
W                  73
OBP             0.329
SLG              0.41
BA              0.258
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.331
OSLG            0.431
Name: 38, dtype: object


Team              DET
League             AL
Year             2011
RS                787
RA                711
W                  95
OBP              0.34
SLG             0.434
BA              0.277
Playoffs            1
RankSeason          4
RankPlayoffs        3
G                 162
OOBP            0.321
OSLG            0.396
Name: 39, dtype: object


Team              FLA
League             NL
Year             2011
RS                625
RA                702
W                  72
OBP             0.318
SLG             0.388
BA              0.247
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.316
OSLG            0.401
Name: 40, dtype: object


Team              HOU
League             NL
Year             2011
RS                615
RA                796
W                  56
OBP             0.311
SLG             0.374
BA              0.258
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.337
OSLG            0.432
Name: 41, dtype: object


Team              KCR
League             AL
Year             2011
RS                730
RA                762
W                  71
OBP             0.329
SLG             0.415
BA              0.275
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.337
OSLG            0.425
Name: 42, dtype: object


Team              LAA
League             AL
Year             2011
RS                667
RA                633
W                  86
OBP             0.313
SLG             0.402
BA              0.253
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.313
OSLG            0.388
Name: 43, dtype: object


Team              LAD
League             NL
Year             2011
RS                644
RA                612
W                  82
OBP             0.322
SLG             0.375
BA              0.257
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP             0.31
OSLG            0.371
Name: 44, dtype: object


Team              MIL
League             NL
Year             2011
RS                721
RA                638
W                  96
OBP             0.325
SLG             0.425
BA              0.261
Playoffs            1
RankSeason          3
RankPlayoffs        3
G                 162
OOBP            0.304
OSLG            0.385
Name: 45, dtype: object


Team              MIN
League             AL
Year             2011
RS                619
RA                804
W                  63
OBP             0.306
SLG              0.36
BA              0.247
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP             0.34
OSLG            0.435
Name: 46, dtype: object


Team              NYM
League             NL
Year             2011
RS                718
RA                742
W                  77
OBP             0.335
SLG             0.391
BA              0.264
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.332
OSLG            0.411
Name: 47, dtype: object


Team              NYY
League             AL
Year             2011
RS                867
RA                657
W                  97
OBP             0.343
SLG             0.444
BA              0.263
Playoffs            1
RankSeason          2
RankPlayoffs        4
G                 162
OOBP            0.322
OSLG            0.399
Name: 48, dtype: object


Team              OAK
League             AL
Year             2011
RS                645
RA                679
W                  74
OBP             0.311
SLG             0.369
BA              0.244
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.317
OSLG            0.378
Name: 49, dtype: object


Team              PHI
League             NL
Year             2011
RS                713
RA                529
W                 102
OBP             0.323
SLG             0.395
BA              0.253
Playoffs            1
RankSeason          1
RankPlayoffs        4
G                 162
OOBP            0.296
OSLG            0.361
Name: 50, dtype: object


Team              PIT
League             NL
Year             2011
RS                610
RA                712
W                  72
OBP             0.309
SLG             0.368
BA              0.244
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.338
OSLG            0.409
Name: 51, dtype: object


Team              SDP
League             NL
Year             2011
RS                593
RA                611
W                  71
OBP             0.305
SLG             0.349
BA              0.237
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.314
OSLG            0.375
Name: 52, dtype: object


Team              SEA
League             AL
Year             2011
RS                556
RA                675
W                  67
OBP             0.292
SLG             0.348
BA              0.233
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP             0.31
OSLG            0.386
Name: 53, dtype: object


Team              SFG
League             NL
Year             2011
RS                570
RA                578
W                  86
OBP             0.303
SLG             0.368
BA              0.242
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.309
OSLG            0.346
Name: 54, dtype: object


Team              STL
League             NL
Year             2011
RS                762
RA                692
W                  90
OBP             0.341
SLG             0.425
BA              0.273
Playoffs            1
RankSeason          7
RankPlayoffs        1
G                 162
OOBP            0.319
OSLG            0.398
Name: 55, dtype: object


Team              TBR
League             AL
Year             2011

In [19]:
for i, row in pit_df.iterrows():
    print(i)
    print(row)
    print(type(row))
    print('\n')

0
Team              ARI
League             NL
Year             2012
RS                734
RA                688
W                  81
OBP             0.328
SLG             0.418
BA              0.259
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.317
OSLG            0.415
Name: 0, dtype: object
<class 'pandas.core.series.Series'>


1
Team              ATL
League             NL
Year             2012
RS                700
RA                600
W                  94
OBP              0.32
SLG             0.389
BA              0.247
Playoffs            1
RankSeason          4
RankPlayoffs        5
G                 162
OOBP            0.306
OSLG            0.378
Name: 1, dtype: object
<class 'pandas.core.series.Series'>


2
Team              BAL
League             AL
Year             2012
RS                712
RA                705
W                  93
OBP             0.311
SLG             0.417
BA              0.247
Playoffs            1
RankSeason          5
RankPlayoffs        4
G                 162
OOBP            0.315
OSLG            0.403
Name: 2, dtype: object
<class 'pandas.core.series.Series'>


3
Team              BOS
League             AL
Year             2012
RS                734
RA                806
W                  69
OBP             0.315
SLG             0.415
BA               0.26
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.331
OSLG            0.428
Name: 3, dtype: object
<class 'pandas.core.series.Series'>


4
Team              CHC
League             NL
Year             2012
RS                613
RA                759
W                  61
OBP             0.302
SLG             0.378
BA               0.24
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.335
OSLG            0.424
Name: 4, dtype: object
<class 'pandas.core.series.Series'>


5
Team              CHW
League             AL
Year             2012
RS                748
RA                676
W                  85
OBP             0.318
SLG             0.422
BA              0.255
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.319
OSLG            0.405
Name: 5, dtype: object
<class 'pandas.core.series.Series'>


6
Team              CIN
League             NL
Year             2012
RS                669
RA                588
W                  97
OBP             0.315
SLG             0.411
BA              0.251
Playoffs            1
RankSeason          2
RankPlayoffs        4
G                 162
OOBP            0.305
OSLG             0.39
Name: 6, dtype: object
<class 'pandas.core.series.Series'>


7
Team              CLE
League             AL
Year             2012
RS                667
RA                845
W                  68
OBP             0.324
SLG             0.381
BA              0.251
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.336
OSLG             0.43
Name: 7, dtype: object
<class 'pandas.core.series.Series'>


8
Team              COL
League             NL
Year             2012
RS                758
RA                890
W                  64
OBP              0.33
SLG             0.436
BA              0.274
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.357
OSLG             0.47
Name: 8, dtype: object
<class 'pandas.core.series.Series'>


9
Team              DET
League             AL
Year             2012
RS                726
RA                670
W                  88
OBP             0.335
SLG             0.422
BA              0.268
Playoffs            1
RankSeason          6
RankPlayoffs        2
G                 162
OOBP            0.314
OSLG            0.402
Name: 9, dtype: object
<class 'pandas.core.series.Series'>


10
Team              HOU
League             NL
Year             2012
RS                583
RA                794
W                  55
OBP             0.302
SLG             0.371
BA              0.236
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.337
OSLG            0.427
Name: 10, dtype: object
<class 'pandas.core.series.Series'>


11
Team              KCR
League             AL
Year             2012
RS                676
RA                746
W                  72
OBP             0.317
SLG               0.4
BA              0.265
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.339
OSLG            0.423
Name: 11, dtype: object
<class 'pandas.core.series.Series'>


12
Team              LAA
League             AL
Year             2012
RS                767
RA                699
W                  89
OBP             0.332
SLG             0.433
BA              0.274
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP             0.31
OSLG            0.403
Name: 12, dtype: object
<class 'pandas.core.series.Series'>


13
Team              LAD
League             NL
Year             2012
RS                637
RA                597
W                  86
OBP             0.317
SLG             0.374
BA              0.252
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP             0.31
OSLG            0.364
Name: 13, dtype: object
<class 'pandas.core.series.Series'>


14
Team              MIA
League             NL
Year             2012
RS                609
RA                724
W                  69
OBP             0.308
SLG             0.382
BA              0.244
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.327
OSLG            0.399
Name: 14, dtype: object
<class 'pandas.core.series.Series'>


15
Team              MIL
League             NL
Year             2012
RS                776
RA                733
W                  83
OBP             0.325
SLG             0.437
BA              0.259
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.326
OSLG            0.414
Name: 15, dtype: object
<class 'pandas.core.series.Series'>


16
Team              MIN
League             AL
Year             2012
RS                701
RA                832
W                  66
OBP             0.325
SLG              0.39
BA               0.26
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.333
OSLG            0.442
Name: 16, dtype: object
<class 'pandas.core.series.Series'>


17
Team              NYM
League             NL
Year             2012
RS                650
RA                709
W                  74
OBP             0.316
SLG             0.386
BA              0.249
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.315
OSLG            0.401
Name: 17, dtype: object
<class 'pandas.core.series.Series'>


18
Team              NYY
League             AL
Year             2012
RS                804
RA                668
W                  95
OBP             0.337
SLG             0.453
BA              0.265
Playoffs            1
RankSeason          3
RankPlayoffs        3
G                 162
OOBP            0.311
OSLG            0.419
Name: 18, dtype: object
<class 'pandas.core.series.Series'>


19
Team              OAK
League             AL
Year             2012
RS                713
RA                614
W                  94
OBP              0.31
SLG             0.404
BA              0.238
Playoffs            1
RankSeason          4
RankPlayoffs        4
G                 162
OOBP            0.306
OSLG            0.378
Name: 19, dtype: object
<class 'pandas.core.series.Series'>


20
Team              PHI
League             NL
Year             2012
RS                684
RA                680
W                  81
OBP             0.317
SLG               0.4
BA              0.255
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.306
OSLG            0.407
Name: 20, dtype: object
<class 'pandas.core.series.Series'>


21
Team              PIT
League             NL
Year             2012
RS                651
RA                674
W                  79
OBP             0.304
SLG             0.395
BA              0.243
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.314
OSLG             0.39
Name: 21, dtype: object
<class 'pandas.core.series.Series'>


22
Team              SDP
League             NL
Year             2012
RS                651
RA                710
W                  76
OBP             0.319
SLG              0.38
BA              0.247
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.319
OSLG            0.398
Name: 22, dtype: object
<class 'pandas.core.series.Series'>


23
Team              SEA
League             AL
Year             2012
RS                619
RA                651
W                  75
OBP             0.296
SLG             0.369
BA              0.234
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.308
OSLG            0.394
Name: 23, dtype: object
<class 'pandas.core.series.Series'>


24
Team              SFG
League             NL
Year             2012
RS                718
RA                649
W                  94
OBP             0.327
SLG             0.397
BA              0.269
Playoffs            1
RankSeason          4
RankPlayoffs        1
G                 162
OOBP            0.313
OSLG            0.393
Name: 24, dtype: object
<class 'pandas.core.series.Series'>


25
Team              STL
League             NL
Year             2012
RS                765
RA                648
W                  88
OBP             0.338
SLG             0.421
BA              0.271
Playoffs            1
RankSeason          6
RankPlayoffs        3
G                 162
OOBP            0.313
OSLG            0.387
Name: 25, dtype: object
<class 'pandas.core.series.Series'>


26
Team              TBR
League             AL
Year             2012
RS                697
RA                577
W                  90
OBP             0.317
SLG             0.394
BA               0.24
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.294
OSLG            0.352
Name: 26, dtype: object
<class 'pandas.core.series.Series'>


27
Team              TEX
League             AL
Year             2012
RS                808
RA                707
W                  93
OBP             0.334
SLG             0.446
BA              0.273
Playoffs            1
RankSeason          5
RankPlayoffs        5
G                 162
OOBP            0.309
OSLG            0.408
Name: 27, dtype: object
<class 'pandas.core.series.Series'>


28
Team              TOR
League             AL
Year             2012
RS                716
RA                784
W                  73
OBP             0.309
SLG             0.407
BA              0.245
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.335
OSLG            0.438
Name: 28, dtype: object
<class 'pandas.core.series.Series'>


29
Team              WSN
League             NL
Year             2012
RS                731
RA                594
W                  98
OBP             0.322
SLG             0.428
BA              0.261
Playoffs            1
RankSeason          1
RankPlayoffs        4
G                 162
OOBP            0.303
OSLG            0.373
Name: 29, dtype: object
<class 'pandas.core.series.Series'>


30
Team              ARI
League             NL
Year             2011
RS                731
RA                662
W                  94
OBP             0.322
SLG             0.413
BA               0.25
Playoffs            1
RankSeason          5
RankPlayoffs        4
G                 162
OOBP            0.316
OSLG            0.409
Name: 30, dtype: object
<class 'pandas.core.series.Series'>


31
Team              ATL
League             NL
Year             2011
RS                641
RA                605
W                  89
OBP             0.308
SLG             0.387
BA              0.243
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP             0.31
OSLG            0.361
Name: 31, dtype: object
<class 'pandas.core.series.Series'>


32
Team              BAL
League             AL
Year             2011
RS                708
RA                860
W                  69
OBP             0.316
SLG             0.413
BA              0.257
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.341
OSLG             0.46
Name: 32, dtype: object
<class 'pandas.core.series.Series'>


33
Team              BOS
League             AL
Year             2011
RS                875
RA                737
W                  90
OBP             0.349
SLG             0.461
BA               0.28
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.322
OSLG            0.392
Name: 33, dtype: object
<class 'pandas.core.series.Series'>


34
Team              CHC
League             NL
Year             2011
RS                654
RA                756
W                  71
OBP             0.314
SLG             0.401
BA              0.256
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.335
OSLG            0.413
Name: 34, dtype: object
<class 'pandas.core.series.Series'>


35
Team              CHW
League             AL
Year             2011
RS                654
RA                706
W                  79
OBP             0.319
SLG             0.388
BA              0.252
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.317
OSLG            0.397
Name: 35, dtype: object
<class 'pandas.core.series.Series'>


36
Team              CIN
League             NL
Year             2011
RS                735
RA                720
W                  79
OBP             0.326
SLG             0.408
BA              0.256
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.325
OSLG            0.415
Name: 36, dtype: object
<class 'pandas.core.series.Series'>


37
Team              CLE
League             AL
Year             2011
RS                704
RA                760
W                  80
OBP             0.317
SLG             0.396
BA               0.25
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.323
OSLG            0.413
Name: 37, dtype: object
<class 'pandas.core.series.Series'>


38
Team              COL
League             NL
Year             2011
RS                735
RA                774
W                  73
OBP             0.329
SLG              0.41
BA              0.258
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.331
OSLG            0.431
Name: 38, dtype: object
<class 'pandas.core.series.Series'>


39
Team              DET
League             AL
Year             2011
RS                787
RA                711
W                  95
OBP              0.34
SLG             0.434
BA              0.277
Playoffs            1
RankSeason          4
RankPlayoffs        3
G                 162
OOBP            0.321
OSLG            0.396
Name: 39, dtype: object
<class 'pandas.core.series.Series'>


40
Team              FLA
League             NL
Year             2011
RS                625
RA                702
W                  72
OBP             0.318
SLG             0.388
BA              0.247
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.316
OSLG            0.401
Name: 40, dtype: object
<class 'pandas.core.series.Series'>


41
Team              HOU
League             NL
Year             2011
RS                615
RA                796
W                  56
OBP             0.311
SLG             0.374
BA              0.258
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.337
OSLG            0.432
Name: 41, dtype: object
<class 'pandas.core.series.Series'>


42
Team              KCR
League             AL
Year             2011
RS                730
RA                762
W                  71
OBP             0.329
SLG             0.415
BA              0.275
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.337
OSLG            0.425
Name: 42, dtype: object
<class 'pandas.core.series.Series'>


43
Team              LAA
League             AL
Year             2011
RS                667
RA                633
W                  86
OBP             0.313
SLG             0.402
BA              0.253
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.313
OSLG            0.388
Name: 43, dtype: object
<class 'pandas.core.series.Series'>


44
Team              LAD
League             NL
Year             2011
RS                644
RA                612
W                  82
OBP             0.322
SLG             0.375
BA              0.257
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP             0.31
OSLG            0.371
Name: 44, dtype: object
<class 'pandas.core.series.Series'>


45
Team              MIL
League             NL
Year             2011
RS                721
RA                638
W                  96
OBP             0.325
SLG             0.425
BA              0.261
Playoffs            1
RankSeason          3
RankPlayoffs        3
G                 162
OOBP            0.304
OSLG            0.385
Name: 45, dtype: object
<class 'pandas.core.series.Series'>


46
Team              MIN
League             AL
Year             2011
RS                619
RA                804
W                  63
OBP             0.306
SLG              0.36
BA              0.247
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP             0.34
OSLG            0.435
Name: 46, dtype: object
<class 'pandas.core.series.Series'>


47
Team              NYM
League             NL
Year             2011
RS                718
RA                742
W                  77
OBP             0.335
SLG             0.391
BA              0.264
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.332
OSLG            0.411
Name: 47, dtype: object
<class 'pandas.core.series.Series'>


48
Team              NYY
League             AL
Year             2011
RS                867
RA                657
W                  97
OBP             0.343
SLG             0.444
BA              0.263
Playoffs            1
RankSeason          2
RankPlayoffs        4
G                 162
OOBP            0.322
OSLG            0.399
Name: 48, dtype: object
<class 'pandas.core.series.Series'>


49
Team              OAK
League             AL
Year             2011
RS                645
RA                679
W                  74
OBP             0.311
SLG             0.369
BA              0.244
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.317
OSLG            0.378
Name: 49, dtype: object
<class 'pandas.core.series.Series'>


50
Team              PHI
League             NL
Year             2011
RS                713
RA                529
W                 102
OBP             0.323
SLG             0.395
BA              0.253
Playoffs            1
RankSeason          1
RankPlayoffs        4

In [22]:
for row_tuple in pit_df.iterrows():
    print(row_tuple)
    print(type(row_tuple))

(0, Team              ARI
League             NL
Year             2012
RS                734
RA                688
W                  81
OBP             0.328
SLG             0.418
BA              0.259
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.317
OSLG            0.415
Name: 0, dtype: object)
<class 'tuple'>
(1, Team              ATL
League             NL
Year             2012
RS                700
RA                600
W                  94
OBP              0.32
SLG             0.389
BA              0.247
Playoffs            1
RankSeason          4
RankPlayoffs        5
G                 162
OOBP            0.306
OSLG            0.378
Name: 1, dtype: object)
<class 'tuple'>
(2, Team              BAL
League             AL
Year             2012
RS                712
RA                705
W                  93
OBP             0.311
SLG             0.417
BA              0.247
Playoffs            1
RankSeason          5
RankPlayoffs        4
G                 162
OOBP            0.315
OSLG            0.403
Name: 2, dtype: object)
<class 'tuple'>
(3, Team              BOS
League             AL
Year             2012
RS                734
RA                806
W                  69
OBP             0.315
SLG             0.415
BA               0.26
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.331
OSLG            0.428
Name: 3, dtype: object)
<class 'tuple'>
(4, Team              CHC
League             NL
Year             2012
RS                613
RA                759
W                  61
OBP             0.302
SLG             0.378
BA               0.24
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.335
OSLG            0.424
Name: 4, dtype: object)
<class 'tuple'>
(5, Team              CHW
League             AL
Year             2012
RS                748
RA                676
W                  85
OBP             0.318
SLG             0.422
BA              0.255
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.319
OSLG            0.405
Name: 5, dtype: object)
<class 'tuple'>
(6, Team              CIN
League             NL
Year             2012
RS                669
RA                588
W                  97
OBP             0.315
SLG             0.411
BA              0.251
Playoffs            1
RankSeason          2
RankPlayoffs        4
G                 162
OOBP            0.305
OSLG             0.39
Name: 6, dtype: object)
<class 'tuple'>
(7, Team              CLE
League             AL
Year             2012
RS                667
RA                845
W                  68
OBP             0.324
SLG             0.381
BA              0.251
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.336
OSLG             0.43
Name: 7, dtype: object)
<class 'tuple'>
(8, Team              COL
League             NL
Year             2012
RS                758
RA                890
W                  64
OBP              0.33
SLG             0.436
BA              0.274
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.357
OSLG             0.47
Name: 8, dtype: object)
<class 'tuple'>
(9, Team              DET
League             AL
Year             2012
RS                726
RA                670
W                  88
OBP             0.335
SLG             0.422
BA              0.268
Playoffs            1
RankSeason          6
RankPlayoffs        2
G                 162
OOBP            0.314
OSLG            0.402
Name: 9, dtype: object)
<class 'tuple'>
(10, Team              HOU
League             NL
Year             2012
RS                583
RA                794
W                  55
OBP             0.302
SLG             0.371
BA              0.236
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.337
OSLG            0.427
Name: 10, dtype: object)
<class 'tuple'>
(11, Team              KCR
League             AL
Year             2012
RS                676
RA                746
W                  72
OBP             0.317
SLG               0.4
BA              0.265
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.339
OSLG            0.423
Name: 11, dtype: object)
<class 'tuple'>
(12, Team              LAA
League             AL
Year             2012
RS                767
RA                699
W                  89
OBP             0.332
SLG             0.433
BA              0.274
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP             0.31
OSLG            0.403
Name: 12, dtype: object)
<class 'tuple'>
(13, Team              LAD
League             NL
Year             2012
RS                637
RA                597
W                  86
OBP             0.317
SLG             0.374
BA              0.252
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP             0.31
OSLG            0.364
Name: 13, dtype: object)
<class 'tuple'>
(14, Team              MIA
League             NL
Year             2012
RS                609
RA                724
W                  69
OBP             0.308
SLG             0.382
BA              0.244
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.327
OSLG            0.399
Name: 14, dtype: object)
<class 'tuple'>
(15, Team              MIL
League             NL
Year             2012
RS                776
RA                733
W                  83
OBP             0.325
SLG             0.437
BA              0.259
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.326
OSLG            0.414
Name: 15, dtype: object)
<class 'tuple'>
(16, Team              MIN
League             AL
Year             2012
RS                701
RA                832
W                  66
OBP             0.325
SLG              0.39
BA               0.26
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.333
OSLG            0.442
Name: 16, dtype: object)
<class 'tuple'>
(17, Team              NYM
League             NL
Year             2012
RS                650
RA                709
W                  74
OBP             0.316
SLG             0.386
BA              0.249
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.315
OSLG            0.401
Name: 17, dtype: object)
<class 'tuple'>
(18, Team              NYY
League             AL
Year             2012
RS                804
RA                668
W                  95
OBP             0.337
SLG             0.453
BA              0.265
Playoffs            1
RankSeason          3
RankPlayoffs        3
G                 162
OOBP            0.311
OSLG            0.419
Name: 18, dtype: object)
<class 'tuple'>
(19, Team              OAK
League             AL
Year             2012
RS                713
RA                614
W                  94
OBP              0.31
SLG             0.404
BA              0.238
Playoffs            1
RankSeason          4
RankPlayoffs        4
G                 162
OOBP            0.306
OSLG            0.378
Name: 19, dtype: object)
<class 'tuple'>
(20, Team              PHI
League             NL
Year             2012
RS                684
RA                680
W                  81
OBP             0.317
SLG               0.4
BA              0.255
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.306
OSLG            0.407
Name: 20, dtype: object)
<class 'tuple'>
(21, Team              PIT
League             NL
Year             2012
RS                651
RA                674
W                  79
OBP             0.304
SLG             0.395
BA              0.243
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.314
OSLG             0.39
Name: 21, dtype: object)
<class 'tuple'>
(22, Team              SDP
League             NL
Year             2012
RS                651
RA                710
W                  76
OBP             0.319
SLG              0.38
BA              0.247
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.319
OSLG            0.398
Name: 22, dtype: object)
<class 'tuple'>
(23, Team              SEA
League             AL
Year             2012
RS                619
RA                651
W                  75
OBP             0.296
SLG             0.369
BA              0.234
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.308
OSLG            0.394
Name: 23, dtype: object)
<class 'tuple'>
(24, Team              SFG
League             NL
Year             2012
RS                718
RA                649
W                  94
OBP             0.327
SLG             0.397
BA              0.269
Playoffs            1
RankSeason          4
RankPlayoffs        1
G                 162
OOBP            0.313
OSLG            0.393
Name: 24, dtype: object)
<class 'tuple'>
(25, Team              STL
League             NL
Year             2012
RS                765
RA                648
W                  88
OBP             0.338
SLG             0.421
BA              0.271
Playoffs            1
RankSeason          6
RankPlayoffs        3
G                 162
OOBP            0.313
OSLG            0.387
Name: 25, dtype: object)
<class 'tuple'>
(26, Team              TBR
League             AL
Year             2012
RS                697
RA                577
W                  90
OBP             0.317
SLG             0.394
BA               0.24
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.294
OSLG            0.352
Name: 26, dtype: object)
<class 'tuple'>
(27, Team              TEX
League             AL
Year             2012
RS                808
RA                707
W                  93
OBP             0.334
SLG             0.446
BA              0.273
Playoffs            1
RankSeason          5
RankPlayoffs        5
G                 162
OOBP            0.309
OSLG            0.408
Name: 27, dtype: object)
<class 'tuple'>
(28, Team              TOR
League             AL
Year             2012
RS                716
RA                784
W                  73
OBP             0.309
SLG             0.407
BA              0.245
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.335
OSLG            0.438
Name: 28, dtype: object)
<class 'tuple'>
(29, Team              WSN
League             NL
Year             2012
RS                731
RA                594
W                  98
OBP             0.322
SLG             0.428
BA              0.261
Playoffs            1
RankSeason          1
RankPlayoffs        4
G                 162
OOBP            0.303
OSLG            0.373
Name: 29, dtype: object)
<class 'tuple'>
(30, Team              ARI
League             NL
Year             2011
RS                731
RA                662
W                  94
OBP             0.322
SLG             0.413
BA               0.25
Playoffs            1
RankSeason          5
RankPlayoffs        4
G                 162
OOBP            0.316
OSLG            0.409
Name: 30, dtype: object)
<class 'tuple'>
(31, Team              ATL
League             NL
Year             2011
RS                641
RA                605
W                  89
OBP             0.308
SLG             0.387
BA              0.243
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP             0.31
OSLG            0.361
Name: 31, dtype: object)
<class 'tuple'>
(32, Team              BAL
League             AL
Year             2011
RS                708
RA                860
W                  69
OBP             0.316
SLG             0.413
BA              0.257
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.341
OSLG             0.46
Name: 32, dtype: object)
<class 'tuple'>
(33, Team              BOS
League             AL
Year             2011
RS                875
RA                737
W                  90
OBP             0.349
SLG             0.461
BA               0.28
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.322
OSLG            0.392
Name: 33, dtype: object)
<class 'tuple'>
(34, Team              CHC
League             NL
Year             2011
RS                654
RA                756
W                  71
OBP             0.314
SLG             0.401
BA              0.256
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.335
OSLG            0.413
Name: 34, dtype: object)
<class 'tuple'>
(35, Team              CHW
League             AL
Year             2011
RS                654
RA                706
W                  79
OBP             0.319
SLG             0.388
BA              0.252
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.317
OSLG            0.397
Name: 35, dtype: object)
<class 'tuple'>
(36, Team              CIN
League             NL
Year             2011
RS                735
RA                720
W                  79
OBP             0.326
SLG             0.408
BA              0.256
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.325
OSLG            0.415
Name: 36, dtype: object)
<class 'tuple'>
(37, Team              CLE
League             AL
Year             2011
RS                704
RA                760
W                  80
OBP             0.317
SLG             0.396
BA               0.25
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.323
OSLG            0.413
Name: 37, dtype: object)
<class 'tuple'>
(38, Team              COL
League             NL
Year             2011
RS                735
RA                774
W                  73
OBP             0.329
SLG              0.41
BA              0.258
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.331
OSLG            0.431
Name: 38, dtype: object)
<class 'tuple'>
(39, Team              DET
League             AL
Year             2011
RS                787
RA                711
W                  95
OBP              0.34
SLG             0.434
BA              0.277
Playoffs            1
RankSeason          4
RankPlayoffs        3
G                 162
OOBP            0.321
OSLG            0.396
Name: 39, dtype: object)
<class 'tuple'>
(40, Team              FLA
League             NL
Year             2011
RS                625
RA                702
W                  72
OBP             0.318
SLG             0.388
BA              0.247
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.316
OSLG            0.401
Name: 40, dtype: object)
<class 'tuple'>
(41, Team              HOU
League             NL
Year             2011
RS                615
RA                796
W                  56
OBP             0.311
SLG             0.374
BA              0.258
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.337
OSLG            0.432
Name: 41, dtype: object)
<class 'tuple'>
(42, Team              KCR
League             AL
Year             2011
RS                730
RA                762
W                  71
OBP             0.329
SLG             0.415
BA              0.275
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.337
OSLG            0.425
Name: 42, dtype: object)
<class 'tuple'>
(43, Team              LAA
League             AL
Year             2011
RS                667
RA                633
W                  86
OBP             0.313
SLG             0.402
BA              0.253
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.313
OSLG            0.388
Name: 43, dtype: object)
<class 'tuple'>
(44, Team              LAD
League             NL
Year             2011
RS                644
RA                612
W                  82
OBP             0.322
SLG             0.375
BA              0.257
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP             0.31
OSLG            0.371
Name: 44, dtype: object)
<class 'tuple'>
(45, Team              MIL
League             NL
Year             2011
RS                721
RA                638
W                  96
OBP             0.325
SLG             0.425
BA              0.261
Playoffs            1
RankSeason          3
RankPlayoffs        3
G                 162
OOBP            0.304
OSLG            0.385
Name: 45, dtype: object)
<class 'tuple'>
(46, Team              MIN
League             AL
Year             2011
RS                619
RA                804
W                  63
OBP             0.306
SLG              0.36
BA              0.247
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP             0.34
OSLG            0.435
Name: 46, dtype: object)
<class 'tuple'>
(47, Team              NYM
League             NL
Year             2011
RS                718
RA                742
W                  77
OBP             0.335
SLG             0.391
BA              0.264
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.332
OSLG            0.411
Name: 47, dtype: object)
<class 'tuple'>
(48, Team              NYY
League             AL
Year             2011
RS                867
RA                657
W                  97
OBP             0.343
SLG             0.444
BA              0.263
Playoffs            1
RankSeason          2
RankPlayoffs        4
G                 162
OOBP            0.322
OSLG            0.399
Name: 48, dtype: object)
<class 'tuple'>
(49, Team              OAK
League             AL
Year             2011
RS                645
RA                679
W                  74
OBP             0.311
SLG             0.369
BA              0.244
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.317
OSLG            0.378
Name: 49, dtype: object)
<class 'tuple'>
(50, Team              PHI
League             NL
Year             2011
RS                713
RA                529
W                 102
OBP             0.323
SLG             0.395
BA              0.253
Playoffs            1
RankSeason          1
RankPlayoffs        4
G                 162
OOBP            0.296
OSLG            0.361
Name: 50, dtype: object)
<class 'tuple'>
(51, Team              PIT
League             NL
Year             2011
RS                610
RA                712
W                  72
OBP             0.309
SLG             0.368
BA              0.244
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.338
OSLG            0.409
Name: 51, dtype: object)
<class 'tuple'>
(52, Team              SDP
League             NL
Year             2011
RS                593
RA                611
W                  71
OBP             0.305
SLG             0.349
BA              0.237
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.314
OSLG            0.375
Name: 52, dtype: object)
<class 'tuple'>
(53, Team              SEA
League             AL
Year             2011

<b> Conclusión : </b>

- .iterrows() devuelve cada fila del DataFrame como una tupla de pares (índice, Serie pandas), puedes dividir esta tupla y utilizar el índice y los valores de la fila por separado (como hiciste con for i,row en pit_df.iterrows()), o puedes mantener el resultado de .iterrows() en forma de tupla (como hiciste con for row_tuple en pit_df.iterrows()).

- Si utiliza i,row, puede acceder a cosas de la fila utilizando corchetes (es decir, row['Equipo']). Si se utiliza row_tuple, habría que especificar a qué elemento de la tupla se quiere acceder antes de coger el nombre del equipo (es decir, row_tuple[1]['Equipo']).

- Con cualquiera de los dos enfoques, el uso de .iterrows() seguirá siendo sustancialmente más rápido que el uso de .iloc

In [5]:
pit_df

,Team,League,Year,RS,RA,W,OBP,SLG,BA,Playoffs,RankSeason,RankPlayoffs,G,OOBP,OSLG
0,ARI,NL,2012,734,688,81,0.328,0.418,0.259,0,NaN,NaN,162,0.317,0.415
1,ATL,NL,2012,700,600,94,0.320,0.389,0.247,1,4.0,5.0,162,0.306,0.378
2,BAL,AL,2012,712,705,93,0.311,0.417,0.247,1,5.0,4.0,162,0.315,0.403
3,BOS,AL,2012,734,806,69,0.315,0.415,0.260,0,NaN,NaN,162,0.331,0.428
4,CHC,NL,2012,613,759,61,0.302,0.378,0.240,0,NaN,NaN,162,0.335,0.424
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1227,PHI,NL,1962,705,759,81,0.330,0.390,0.260,0,NaN,NaN,161,NaN,NaN
1228,PIT,NL,1962,706,626,93,0.321,0.394,0.268,0,NaN,NaN,161,NaN,NaN
1229,SFG,NL,1962,878,690,103,0.341,0.441,0.278,1,1.0,2.0,165,NaN,NaN
1230,STL,NL,1962,774,664,84,0.335,0.394,0.271,0,NaN,NaN,163,NaN,NaN
1231,WSA,AL,1962,599,716,60,0.308,0.373,0.250,0,NaN,NaN,162,NaN,NaN

<b> .itertuples() </b>

- Para iterar

In [30]:
for row in pit_df.itertuples():
    print(row)
    print('\n')

Pandas(Index=0, Team='ARI', League='NL', Year=2012, RS=734, RA=688, W=81, OBP=0.32799999999999996, SLG=0.418, BA=0.259, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.317, OSLG=0.415)


Pandas(Index=1, Team='ATL', League='NL', Year=2012, RS=700, RA=600, W=94, OBP=0.32, SLG=0.389, BA=0.247, Playoffs=1, RankSeason=4.0, RankPlayoffs=5.0, G=162, OOBP=0.306, OSLG=0.37799999999999995)


Pandas(Index=2, Team='BAL', League='AL', Year=2012, RS=712, RA=705, W=93, OBP=0.311, SLG=0.41700000000000004, BA=0.247, Playoffs=1, RankSeason=5.0, RankPlayoffs=4.0, G=162, OOBP=0.315, OSLG=0.40299999999999997)


Pandas(Index=3, Team='BOS', League='AL', Year=2012, RS=734, RA=806, W=69, OBP=0.315, SLG=0.415, BA=0.26, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.331, OSLG=0.428)


Pandas(Index=4, Team='CHC', League='NL', Year=2012, RS=613, RA=759, W=61, OBP=0.302, SLG=0.37799999999999995, BA=0.24, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.335, OSLG=0.424)


Pandas(Index=5, Team='CHW', League='AL', Year=2012, RS=748, RA=676, W=85, OBP=0.318, SLG=0.42200000000000004, BA=0.255, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.319, OSLG=0.405)


Pandas(Index=6, Team='CIN', League='NL', Year=2012, RS=669, RA=588, W=97, OBP=0.315, SLG=0.41100000000000003, BA=0.251, Playoffs=1, RankSeason=2.0, RankPlayoffs=4.0, G=162, OOBP=0.305, OSLG=0.39)


Pandas(Index=7, Team='CLE', League='AL', Year=2012, RS=667, RA=845, W=68, OBP=0.324, SLG=0.381, BA=0.251, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.336, OSLG=0.43)


Pandas(Index=8, Team='COL', League='NL', Year=2012, RS=758, RA=890, W=64, OBP=0.33, SLG=0.436, BA=0.27399999999999997, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.35700000000000004, OSLG=0.47)


Pandas(Index=9, Team='DET', League='AL', Year=2012, RS=726, RA=670, W=88, OBP=0.335, SLG=0.42200000000000004, BA=0.268, Playoffs=1, RankSeason=6.0, RankPlayoffs=2.0, G=162, OOBP=0.314, OSLG=0.402)


Pandas(Index=10, Team='HOU', League='NL', Year=2012, RS=583, RA=794, W=55, OBP=0.302, SLG=0.371, BA=0.23600000000000002, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.337, OSLG=0.42700000000000005)


Pandas(Index=11, Team='KCR', League='AL', Year=2012, RS=676, RA=746, W=72, OBP=0.317, SLG=0.4, BA=0.265, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.33899999999999997, OSLG=0.423)


Pandas(Index=12, Team='LAA', League='AL', Year=2012, RS=767, RA=699, W=89, OBP=0.332, SLG=0.433, BA=0.27399999999999997, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.31, OSLG=0.40299999999999997)


Pandas(Index=13, Team='LAD', League='NL', Year=2012, RS=637, RA=597, W=86, OBP=0.317, SLG=0.374, BA=0.252, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.31, OSLG=0.364)


Pandas(Index=14, Team='MIA', League='NL', Year=2012, RS=609, RA=724, W=69, OBP=0.308, SLG=0.382, BA=0.244, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.327, OSLG=0.39899999999999997)


Pandas(Index=15, Team='MIL', League='NL', Year=2012, RS=776, RA=733, W=83, OBP=0.325, SLG=0.43700000000000006, BA=0.259, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.326, OSLG=0.414)


Pandas(Index=16, Team='MIN', League='AL', Year=2012, RS=701, RA=832, W=66, OBP=0.325, SLG=0.39, BA=0.26, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.33299999999999996, OSLG=0.442)


Pandas(Index=17, Team='NYM', League='NL', Year=2012, RS=650, RA=709, W=74, OBP=0.316, SLG=0.386, BA=0.249, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.315, OSLG=0.401)


Pandas(Index=18, Team='NYY', League='AL', Year=2012, RS=804, RA=668, W=95, OBP=0.337, SLG=0.45299999999999996, BA=0.265, Playoffs=1, RankSeason=3.0, RankPlayoffs=3.0, G=162, OOBP=0.311, OSLG=0.419)


Pandas(Index=19, Team='OAK', League='AL', Year=2012, RS=713, RA=614, W=94, OBP=0.31, SLG=0.40399999999999997, BA=0.23800000000000002, Playoffs=1, RankSeason=4.0, RankPlayoffs=4.0, G=162, OOBP=0.306, OSLG=0.37799999999999995)


Pandas(Index=20, Team='PHI', League='NL', Year=2012, RS=684, RA=680, W=81, OBP=0.317, SLG=0.4, BA=0.255, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.306, OSLG=0.40700000000000003)


Pandas(Index=21, Team='PIT', League='NL', Year=2012, RS=651, RA=674, W=79, OBP=0.304, SLG=0.395, BA=0.243, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.314, OSLG=0.39)


Pandas(Index=22, Team='SDP', League='NL', Year=2012, RS=651, RA=710, W=76, OBP=0.319, SLG=0.38, BA=0.247, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.319, OSLG=0.39799999999999996)


Pandas(Index=23, Team='SEA', League='AL', Year=2012, RS=619, RA=651, W=75, OBP=0.29600000000000004, SLG=0.369, BA=0.23399999999999999, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.308, OSLG=0.39399999999999996)


Pandas(Index=24, Team='SFG', League='NL', Year=2012, RS=718, RA=649, W=94, OBP=0.327, SLG=0.397, BA=0.26899999999999996, Playoffs=1, RankSeason=4.0, RankPlayoffs=1.0, G=162, OOBP=0.313, OSLG=0.39299999999999996)


Pandas(Index=25, Team='STL', League='NL', Year=2012, RS=765, RA=648, W=88, OBP=0.33799999999999997, SLG=0.42100000000000004, BA=0.271, Playoffs=1, RankSeason=6.0, RankPlayoffs=3.0, G=162, OOBP=0.313, OSLG=0.387)


Pandas(Index=26, Team='TBR', League='AL', Year=2012, RS=697, RA=577, W=90, OBP=0.317, SLG=0.39399999999999996, BA=0.24, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.294, OSLG=0.35200000000000004)


Pandas(Index=27, Team='TEX', League='AL', Year=2012, RS=808, RA=707, W=93, OBP=0.33399999999999996, SLG=0.446, BA=0.273, Playoffs=1, RankSeason=5.0, RankPlayoffs=5.0, G=162, OOBP=0.309, OSLG=0.408)


Pandas(Index=28, Team='TOR', League='AL', Year=2012, RS=716, RA=784, W=73, OBP=0.309, SLG=0.40700000000000003, BA=0.245, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.335, OSLG=0.43799999999999994)


Pandas(Index=29, Team='WSN', League='NL', Year=2012, RS=731, RA=594, W=98, OBP=0.322, SLG=0.428, BA=0.261, Playoffs=1, RankSeason=1.0, RankPlayoffs=4.0, G=162, OOBP=0.303, OSLG=0.373)


Pandas(Index=30, Team='ARI', League='NL', Year=2011, RS=731, RA=662, W=94, OBP=0.322, SLG=0.413, BA=0.25, Playoffs=1, RankSeason=5.0, RankPlayoffs=4.0, G=162, OOBP=0.316, OSLG=0.409)


Pandas(Index=31, Team='ATL', League='NL', Year=2011, RS=641, RA=605, W=89, OBP=0.308, SLG=0.387, BA=0.243, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.31, OSLG=0.361)


Pandas(Index=32, Team='BAL', League='AL', Year=2011, RS=708, RA=860, W=69, OBP=0.316, SLG=0.413, BA=0.257, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.341, OSLG=0.46)


Pandas(Index=33, Team='BOS', League='AL', Year=2011, RS=875, RA=737, W=90, OBP=0.349, SLG=0.461, BA=0.28, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.322, OSLG=0.392)


Pandas(Index=34, Team='CHC', League='NL', Year=2011, RS=654, RA=756, W=71, OBP=0.314, SLG=0.401, BA=0.256, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.335, OSLG=0.413)


Pandas(Index=35, Team='CHW', League='AL', Year=2011, RS=654, RA=706, W=79, OBP=0.319, SLG=0.38799999999999996, BA=0.252, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.317, OSLG=0.397)


Pandas(Index=36, Team='CIN', League='NL', Year=2011, RS=735, RA=720, W=79, OBP=0.326, SLG=0.408, BA=0.256, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.325, OSLG=0.415)


Pandas(Index=37, Team='CLE', League='AL', Year=2011, RS=704, RA=760, W=80, OBP=0.317, SLG=0.396, BA=0.25, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.32299999999999995, OSLG=0.413)


Pandas(Index=38, Team='COL', League='NL', Year=2011, RS=735, RA=774, W=73, OBP=0.32899999999999996, SLG=0.41, BA=0.258, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.331, OSLG=0.431)


Pandas(Index=39, Team='DET', League='AL', Year=2011, RS=787, RA=711, W=95, OBP=0.34, SLG=0.434, BA=0.27699999999999997, Playoffs=1, RankSeason=4.0, RankPlayoffs=3.0, G=162, OOBP=0.321, OSLG=0.396)


Pandas(Index=40, Team='FLA', League='NL', Year=2011, RS=625, RA=702, W=72, OBP=0.318, SLG=0.38799999999999996, BA=0.247, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.316, OSLG=0.401)


Pandas(Index=41, Team='HOU', League='NL', Year=2011, RS=615, RA=796, W=56, OBP=0.311, SLG=0.374, BA=0.258, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.337, OSLG=0.43200000000000005)


Pandas(Index=42, Team='KCR', League='AL', Year=2011, RS=730, RA=762, W=71, OBP=0.32899999999999996, SLG=0.415, BA=0.275, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.337, OSLG=0.425)


Pandas(Index=43, Team='LAA', League='AL', Year=2011, RS=667, RA=633, W=86, OBP=0.313, SLG=0.402, BA=0.253, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.313, OSLG=0.38799999999999996)


Pandas(Index=44, Team='LAD', League='NL', Year=2011, RS=644, RA=612, W=82, OBP=0.322, SLG=0.375, BA=0.257, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=161, OOBP=0.31, OSLG=0.371)


Pandas(Index=45, Team='MIL', League='NL', Year=2011, RS=721, RA=638, W=96, OBP=0.325, SLG=0.425, BA=0.261, Playoffs=1, RankSeason=3.0, RankPlayoffs=3.0, G=162, OOBP=0.304, OSLG=0.385)


Pandas(Index=46, Team='MIN', League='AL', Year=2011, RS=619, RA=804, W=63, OBP=0.306, SLG=0.36, BA=0.247, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.34, OSLG=0.435)


Pandas(Index=47, Team='NYM', League='NL', Year=2011, RS=718, RA=742, W=77, OBP=0.335, SLG=0.391, BA=0.264, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.332, OSLG=0.41100000000000003)


Pandas(Index=48, Team='NYY', League='AL', Year=2011, RS=867, RA=657, W=97, OBP=0.34299999999999997, SLG=0.444, BA=0.263, Playoffs=1, RankSeason=2.0, RankPlayoffs=4.0, G=162, OOBP=0.322, OSLG=0.39899999999999997)


Pandas(Index=49, Team='OAK', League='AL', Year=2011, RS=645, RA=679, W=74, OBP=0.311, SLG=0.369, BA=0.244, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.317, OSLG=0.37799999999999995)


Pandas(Index=50, Team='PHI', League='NL', Year=2011, RS=713, RA=529, W=102, OBP=0.32299999999999995, SLG=0.395, BA=0.253, Playoffs=1, RankSeason=1.0, RankPlayoffs=4.0, G=162, OOBP=0.29600000000000004, OSLG=0.361)


Pandas(Index=51, Team='PIT', League='NL', Year=2011, RS=610, RA=712, W=72, OBP=0.309, SLG=0.368, BA=0.244, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.33799999999999997, OSLG=0.409)


Pandas(Index=52, Team='SDP', League='NL', Year=2011, RS=593, RA=611, W=71, OBP=0.305, SLG=0.349, BA=0.237, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.314, OSLG=0.375)


Pandas(Index=53, Team='SEA', League='AL', Year=2011, RS=556, RA=675, W=67, OBP=0.292, SLG=0.348, BA=0.233, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.31, OSLG=0.386)


Pandas(Index=54, Team='SFG', League='NL', Year=2011, RS=570, RA=578, W=86, OBP=0.303, SLG=0.368, BA=0.242, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.309, OSLG=0.34600000000000003)


Pandas(Index=55, Team='STL', League='NL', Year=2011, RS=762, RA=692, W=90, OBP=0.341, SLG=0.425, BA=0.273, Playoffs=1, RankSeason=7.0, RankPlayoffs=1.0, G=162, OOBP=0.319, OSLG=0.39799999999999996)


Pandas(Index=56, Team='TBR', League='AL', Year=2011, RS=707, RA=614, W=91, OBP=0.322, SLG=0.402, BA=0.244, Playoffs=1, RankSeason=6.0, RankPlayoffs=4.0, G=162, OOBP=0.303, OSLG=0.38299999999999995)


Pandas(Index=57, Team='TEX', League='AL', Year=2011, RS=855, RA=677, W=96, OBP=0.34, SLG=0.46, BA=0.28300000000000003, Playoffs=1, RankSeason=3.0, RankPlayoffs=2.0, G=162, OOBP=0.307, OSLG=0.392)


Pandas(Index=58, Team='TOR', League='AL', Year=2011, RS=743, RA=761, W=81, OBP=0.317, SLG=0.413, BA=0.249, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.32799999999999996, OSLG=0.419)


Pandas(Index=59, Team='WSN', League='NL', Year=2011, RS=624, RA=643, W=80, OBP=0.309, SLG=0.38299999999999995, BA=0.242, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=161, OOBP=0.319, OSLG=0.382)


Pandas(Index=60, Team='ARI', League='NL', Year=2010, RS=713, RA=836, W=65, OBP=0.325, SLG=0.41600000000000004, BA=0.25, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.34, OSLG=0.44799999999999995)


Pandas(Index=61, Team='ATL', League='NL', Year=2010, RS=738, RA=629, W=91, OBP=0.33899999999999997, SLG=0.401, BA=0.258, Playoffs=1, RankSeason=6.0, RankPlayoffs=4.0, G=162, OOBP=0.314, OSLG=0.376)


Pandas(Index=62, Team='BAL', League='AL', Year=2010, RS=613, RA=785, W=66, OBP=0.316, SLG=0.386, BA=0.259, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.336, OSLG=0.434)


Pandas(Index=63, Team='BOS', League='AL', Year=2010, RS=818, RA=744, W=89, OBP=0.33899999999999997, SLG=0.451, BA=0.268, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.327, OSLG=0.39899999999999997)


Pandas(Index=64, Team='CHC', League='NL', Year=2010, RS=685, RA=767, W=75, OBP=0.32, SLG=0.401, BA=0.257, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.33399999999999996, OSLG=0.39799999999999996)


Pandas(Index=65, Team='CHW', League='AL', Year=2010, RS=752, RA=704, W=88, OBP=0.332, SLG=0.42, BA=0.268, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.325, OSLG=0.395)


Pandas(Index=66, Team='CIN', League='NL', Year=2010, RS=790, RA=685, W=91, OBP=0.33799999999999997, SLG=0.436, BA=0.272, Playoffs=1, RankSeason=6.0, RankPlayoffs=4.0, G=162, OOBP=0.32299999999999995, OSLG=0.396)


Pandas(Index=67, Team='CLE', League='AL', Year=2010, RS=646, RA=752, W=69, OBP=0.322, SLG=0.37799999999999995, BA=0.248, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.342, OSLG=0.41600000000000004)


Pandas(Index=68, Team='COL', League='NL', Year=2010, RS=770, RA=717, W=83, OBP=0.336, SLG=0.425, BA=0.263, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.326, OSLG=0.397)


Pandas(Index=69, Team='DET', League='AL', Year=2010, RS=751, RA=743, W=81, OBP=0.335, SLG=0.415, BA=0.268, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.332, OSLG=0.4)


Pandas(Index=70, Team='FLA', League='NL', Year=2010, RS=719, RA=717, W=80, OBP=0.321, SLG=0.40299999999999997, BA=0.254, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.331, OSLG=0.39799999999999996)


Pandas(Index=71, Team='HOU', League='NL', Year=2010, RS=611, RA=729, W=76, OBP=0.303, SLG=0.36200000000000004, BA=0.247, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.33, OSLG=0.402)


Pandas(Index=72, Team='KCR', League='AL', Year=2010, RS=676, RA=845, W=67, OBP=0.331, SLG=0.39899999999999997, BA=0.27399999999999997, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.342, OSLG=0.435)


Pandas(Index=73, Team='LAA', League='AL', Year=2010, RS=681, RA=702, W=80, OBP=0.311, SLG=0.39, BA=0.248, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.327, OSLG=0.40299999999999997)


Pandas(Index=74, Team='LAD', League='NL', Year=2010, RS=667, RA=692, W=80, OBP=0.322, SLG=0.379, BA=0.252, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.316, OSLG=0.37799999999999995)


Pandas(Index=75, Team='MIL', League='NL', Year=2010, RS=750, RA=804, W=77, OBP=0.335, SLG=0.424, BA=0.262, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.33799999999999997, OSLG=0.42700000000000005)


Pandas(Index=76, Team='MIN', League='AL', Year=2010, RS=781, RA=671, W=94, OBP=0.341, SLG=0.42200000000000004, BA=0.273, Playoffs=1, RankSeason=4.0, RankPlayoffs=4.0, G=162, OOBP=0.317, OSLG=0.41700000000000004)


Pandas(Index=77, Team='NYM', League='NL', Year=2010, RS=656, RA=652, W=79, OBP=0.314, SLG=0.38299999999999995, BA=0.249, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.33, OSLG=0.39399999999999996)


Pandas(Index=78, Team='NYY', League='AL', Year=2010, RS=859, RA=693, W=95, OBP=0.35, SLG=0.436, BA=0.267, Playoffs=1, RankSeason=3.0, RankPlayoffs=3.0, G=162, OOBP=0.322, OSLG=0.39899999999999997)


Pandas(Index=79, Team='OAK', League='AL', Year=2010, RS=663, RA=626, W=81, OBP=0.324, SLG=0.37799999999999995, BA=0.256, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.313, OSLG=0.379)


Pandas(Index=80, Team='PHI', League='NL', Year=2010, RS=772, RA=640, W=97, OBP=0.332, SLG=0.413, BA=0.26, Playoffs=1, RankSeason=1.0, RankPlayoffs=3.0, G=162, OOBP=0.311, OSLG=0.405)


Pandas(Index=81, Team='PIT', League='NL', Year=2010, RS=587, RA=866, W=57, OBP=0.304, SLG=0.373, BA=0.242, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.348, OSLG=0.449)


Pandas(Index=82, Team='SDP', League='NL', Year=2010, RS=665, RA=581, W=90, OBP=0.317, SLG=0.371, BA=0.24600000000000002, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.308, OSLG=0.368)


Pandas(Index=83, Team='SEA', League='AL', Year=2010, RS=513, RA=698, W=61, OBP=0.298, SLG=0.33899999999999997, BA=0.23600000000000002, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.313, OSLG=0.401)


Pandas(Index=84, Team='SFG', League='NL', Year=2010, RS=697, RA=583, W=92, OBP=0.321, SLG=0.408, BA=0.257, Playoffs=1, RankSeason=5.0, RankPlayoffs=1.0, G=162, OOBP=0.313, OSLG=0.37)


Pandas(Index=85, Team='STL', League='NL', Year=2010, RS=736, RA=641, W=86, OBP=0.332, SLG=0.402, BA=0.263, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.319, OSLG=0.387)


Pandas(Index=86, Team='TBR', League='AL', Year=2010, RS=802, RA=649, W=96, OBP=0.33299999999999996, SLG=0.40299999999999997, BA=0.247, Playoffs=1, RankSeason=2.0, RankPlayoffs=4.0, G=162, OOBP=0.308, OSLG=0.40399999999999997)


Pandas(Index=87, Team='TEX', League='AL', Year=2010, RS=787, RA=687, W=90, OBP=0.33799999999999997, SLG=0.419, BA=0.276, Playoffs=1, RankSeason=7.0, RankPlayoffs=2.0, G=162, OOBP=0.319, OSLG=0.39)


Pandas(Index=88, Team='TOR', League='AL', Year=2010, RS=755, RA=728, W=85, OBP=0.312, SLG=0.45399999999999996, BA=0.248, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.326, OSLG=0.405)


Pandas(Index=89, Team='WSN', League='NL', Year=2010, RS=655, RA=742, W=69, OBP=0.318, SLG=0.39, BA=0.25, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.33, OSLG=0.41)


Pandas(Index=90, Team='ARI', League='NL', Year=2009, RS=720, RA=782, W=70, OBP=0.324, SLG=0.418, BA=0.253, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.33, OSLG=0.419)


Pandas(Index=91, Team='ATL', League='NL', Year=2009, RS=735, RA=641, W=86, OBP=0.33899999999999997, SLG=0.405, BA=0.263, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.32299999999999995, OSLG=0.39)


Pandas(Index=92, Team='BAL', League='AL', Year=2009, RS=741, RA=876, W=64, OBP=0.332, SLG=0.415, BA=0.268, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.353, OSLG=0.47600000000000003)


Pandas(Index=93, Team='BOS', League='AL', Year=2009, RS=872, RA=736, W=95, OBP=0.35200000000000004, SLG=0.45399999999999996, BA=0.27, Playoffs=1, RankSeason=3.0, RankPlayoffs=4.0, G=162, OOBP=0.335, OSLG=0.42200000000000004)


Pandas(Index=94, Team='CHC', League='NL', Year=2009, RS=707, RA=672, W=83, OBP=0.332, SLG=0.40700000000000003, BA=0.255, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=161, OOBP=0.324, OSLG=0.391)


Pandas(Index=95, Team='CHW', League='AL', Year=2009, RS=724, RA=732, W=79, OBP=0.32899999999999996, SLG=0.41100000000000003, BA=0.258, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.325, OSLG=0.414)


Pandas(Index=96, Team='CIN', League='NL', Year=2009, RS=673, RA=723, W=78, OBP=0.318, SLG=0.39399999999999996, BA=0.247, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.33299999999999996, OSLG=0.418)


Pandas(Index=97, Team='CLE', League='AL', Year=2009, RS=773, RA=865, W=65, OBP=0.33899999999999997, SLG=0.41700000000000004, BA=0.264, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.35100000000000003, OSLG=0.44299999999999995)


Pandas(Index=98, Team='COL', League='NL', Year=2009, RS=804, RA=715, W=92, OBP=0.34299999999999997, SLG=0.441, BA=0.261, Playoffs=1, RankSeason=5.0, RankPlayoffs=4.0, G=162, OOBP=0.32799999999999996, OSLG=0.405)



In [35]:
for row in pit_df.itertuples():
    i = row[0]
    team = row[1]
    year = row[3]
    print(i, team, year)
    print('\n')

0 ARI 2012


1 ATL 2012


2 BAL 2012


3 BOS 2012


4 CHC 2012


5 CHW 2012


6 CIN 2012


7 CLE 2012


8 COL 2012


9 DET 2012


10 HOU 2012


11 KCR 2012


12 LAA 2012


13 LAD 2012


14 MIA 2012


15 MIL 2012


16 MIN 2012


17 NYM 2012


18 NYY 2012


19 OAK 2012


20 PHI 2012


21 PIT 2012


22 SDP 2012


23 SEA 2012


24 SFG 2012


25 STL 2012


26 TBR 2012


27 TEX 2012


28 TOR 2012


29 WSN 2012


30 ARI 2011


31 ATL 2011


32 BAL 2011


33 BOS 2011


34 CHC 2011


35 CHW 2011


36 CIN 2011


37 CLE 2011


38 COL 2011


39 DET 2011


40 FLA 2011


41 HOU 2011


42 KCR 2011


43 LAA 2011


44 LAD 2011


45 MIL 2011


46 MIN 2011


47 NYM 2011


48 NYY 2011


49 OAK 2011


50 PHI 2011


51 PIT 2011


52 SDP 2011


53 SEA 2011


54 SFG 2011


55 STL 2011


56 TBR 2011


57 TEX 2011


58 TOR 2011


59 WSN 2011


60 ARI 2010


61 ATL 2010


62 BAL 2010


63 BOS 2010


64 CHC 2010


65 CHW 2010


66 CIN 2010


67 CLE 2010


68 COL 2010


69 DET 2010


70 FLA 2010


71 HOU 2010


72 KCR 2010


73 LAA 2010


74 LAD 2010


75 MIL 2010


76 MIN 2010


77 NYM 2010


78 NYY 2010


79 OAK 2010


80 PHI 2010


81 PIT 2010


82 SDP 2010


83 SEA 2010


84 SFG 2010


85 STL 2010


86 TBR 2010


87 TEX 2010


88 TOR 2010


89 WSN 2010


90 ARI 2009


91 ATL 2009


92 BAL 2009


93 BOS 2009


94 CHC 2009


95 CHW 2009


96 CIN 2009


97 CLE 2009


98 COL 2009


99 DET 2009


100 FLA 2009


101 HOU 2009


102 KCR 2009


103 LAA 2009


104 LAD 2009


105 MIL 2009


106 MIN 2009


107 NYM 2009


108 NYY 2009


109 OAK 2009


110 PHI 2009


111 PIT 2009


112 SDP 2009


113 SEA 2009


114 SFG 2009


115 STL 2009


116 TBR 2009


117 TEX 2009


118 TOR 2009


119 WSN 2009


120 ARI 2008


121 ATL 2008


122 BAL 2008


123 BOS 2008


124 CHC 2008


125 CHW 2008


126 CIN 2008


127 CLE 2008


128 COL 2008


129 DET 2008


130 FLA 2008


131 HOU 2008


132 KCR 2008


133 LAA 2008


134 LAD 2008


135 MIL 2008


136 MIN 2008


137 NYM 2008


138 NYY 2008


139 OAK 2008


140 PHI 2008


141 PIT 2008


142 SDP 2008


143 SEA 2008


144 SFG 2008


145 STL 2008


146 TBR 2008


147 TEX 2008


148 TOR 2008


149 WSN 2008


150 ARI 2007


151 ATL 2007


152 BAL 2007


153 BOS 2007


154 CHC 2007


155 CHW 2007


156 CIN 2007


157 CLE 2007


158 COL 2007


159 DET 2007


160 FLA 2007


161 HOU 2007


162 KCR 2007


163 LAA 2007


164 LAD 2007


165 MIL 2007


166 MIN 2007


167 NYM 2007


168 NYY 2007


169 OAK 2007


170 PHI 2007


171 PIT 2007


172 SDP 2007


173 SEA 2007


174 SFG 2007


175 STL 2007


176 TBD 2007


177 TEX 2007


178 TOR 2007


179 WSN 2007


180 ARI 2006


181 ATL 2006


182 BAL 2006


183 BOS 2006


184 CHC 2006


185 CHW 2006


186 CIN 2006


187 CLE 2006


188 COL 2006


189 DET 2006


190 FLA 2006


191 HOU 2006


192 KCR 2006


193 LAA 2006


194 LAD 2006


195 MIL 2006


196 MIN 2006


197 NYM 2006


198 NYY 2006


199 OAK 2006


200 PHI 2006


201 PIT 2006


202 SDP 2006


203 SEA 2006


204 SFG 2006


205 STL 2006


206 TBD 2006


207 TEX 2006


208 TOR 2006


209 WSN 2006


210 ARI 2005


211 ATL 2005


212 BAL 2005


213 BOS 2005


214 CHC 2005


215 CHW 2005


216 CIN 2005


217 CLE 2005


218 COL 2005


219 DET 2005


220 FLA 2005


221 HOU 2005


222 KCR 2005


223 LAA 2005


224 LAD 2005


225 MIL 2005


226 MIN 2005


227 NYM 2005


228 NYY 2005


229 OAK 2005


230 PHI 2005


231 PIT 2005


232 SDP 2005


233 SEA 2005


234 SFG 2005


235 STL 2005


236 TBD 2005


237 TEX 2005


238 TOR 2005


239 WSN 2005


240 ANA 2004


241 ARI 2004


242 ATL 2004


243 BAL 2004


244 BOS 2004


245 CHC 2004


246 CHW 2004


247 CIN 2004


248 CLE 2004


249 COL 2004


250 DET 2004


251 FLA 2004


252 HOU 2004


253 KCR 2004


254 LAD 2004


255 MIL 2004


256 MIN 2004


257 MON 2004


258 NYM 2004


259 NYY 2004


260 OAK 2004


261 PHI 2004


262 PIT 2004


263 SDP 2004


264 SEA 2004


265 SFG 2004


266 STL 2004


267 TBD 2004


268 TEX 2004


269 TOR 2004


270 ANA 2003


271 ARI 2003


272 ATL 2003


273 BAL 2003


274 BOS 2003


275 CHC 2003


276 CHW 2003


277 CIN 2003


278 CLE 2003


279 COL 2003


280 DET 2003


281 FLA 2003


282 HOU 2003


283 KCR 2003


284 LAD 2003


285 MIL 2003


286 MIN 2003


287 MON 2003


288 NYM 2003


289 NYY 2003


290 OAK 2003


291 PHI 2003


292 PIT 2003


293 SDP 2003


294 SEA 2003


295 SFG 2003


296 STL 2003


297 TBD 2003


298 TEX 2003


299 TOR 2003


300 ANA 2002


301 ARI 2002


302 ATL 2002


303 BAL 2002


304 BOS 2002


305 CHC 2002


306 CHW 2002


307 CIN 2002


308 CLE 2002


309 COL 2002


310 DET 2002


311 FLA 2002


312 HOU 2002


313 KCR 2002


314 LAD 2002


315 MIL 2002


316 MIN 2002


317 MON 2002


318 NYM 2002


319 NYY 2002


320 OAK 2002


321 PHI 2002


322 PIT 2002


323 SDP 2002


324 SEA 2002


325 SFG 2002


326 STL 2002


327 TBD 2002


328 TEX 2002


329 TOR 2002


330 ANA 2001


331 ARI 2001


332 ATL 2001


333 BAL 2001


334 BOS 2001


335 CHC 2001


336 CHW 2001


337 CIN 2001


338 CLE 2001


339 COL 2001


340 DET 2001


341 FLA 2001


342 HOU 2001


343 KCR 2001


344 LAD 2001


345 MIL 2001


346 MIN 2001


347 MON 2001


348 NYM 2001


349 NYY 2001


350 OAK 2001


351 PHI 2001


352 PIT 2001


353 SDP 2001


354 SEA 2001


355 SFG 2001


356 STL 2001


357 TBD 2001


358 TEX 2001


359 TOR 2001


360 ANA 2000


361 ARI 2000


362 ATL 2000


363 BAL 2000


364 BOS 2000


365 CHC 2000


366 CHW 2000


367 CIN 2000


368 CLE 2000


369 COL 2000


370 DET 2000


371 FLA 2000


372 HOU 2000


373 KCR 2000


374 LAD 2000


375 MIL 2000


376 MIN 2000


377 MON 2000


378 NYM 2000


379 NYY 2000


380 OAK 2000


381 PHI 2000


382 PIT 2000


383 SDP 2000


384 SEA 2000


385 SFG 2000


386 STL 2000


387 TBD 2000


388 TEX 2000


389 TOR 2000


390 ANA 1999


391 ARI 1999


392 ATL 1999


393 BAL 1999


394 BOS 1999


395 CHC 1999


396 CHW 1999


397 CIN 1999


398 CLE 1999


399 COL 1999


400 DET 1999


401 FLA 1999


402 HOU 1999


403 KCR 1999


404 LAD 1999


405 MIL 1999


406 MIN 1999


407 MON 1999


408 NYM 1999


409 NYY 1999


410 OAK 1999


411 PHI 1999


412 PIT 1999


413 SDP 1999


414 SEA 1999


415 SFG 1999


416 STL 1999


417 TBD 1999


418 TEX 1999


419 TOR 1999


420 ANA 1998


421 ARI 1998


422 ATL 1998


423 BAL 1998


424 BOS 1998


425 CHC 1998


426 CHW 1998


427 CIN 1998


428 CLE 1998


429 COL 1998


430 DET 1998


431 FLA 1998


432 HOU 1998


433 KCR 1998


434 LAD 1998


435 MIL 1998


436 MIN 1998


437 MON 1998


438 NYM 1998


439 NYY 1998


440 OAK 1998


441 PHI 1998


442 PIT 1998


443 SDP 1998


444 SEA 1998


445 SFG 1998


446 STL 1998


447 TBD 1998


448 TEX 1998


449 TOR 1998


450 ANA 1997


451 ATL 1997


452 BAL 1997


453 BOS 1997


454 CHC 1997


455 CHW 1997


456 CIN 1997


457 CLE 1997


458 COL 1997


459 DET 1997


460 FLA 1997


461 HOU 1997


462 KCR 1997


463 LAD 1997


464 MIL 1997


465 MIN 1997


466 MON 1997


467 NYM 1997


468 NYY 1997


469 OAK 1997


470 PHI 1997


471 PIT 1997


472 SDP 1997


473 SEA 1997


474 SFG 1997


475 STL 1997


476 TEX 1997


477 TOR 1997


478 ATL 1996


479 BAL 1996


480 BOS 1996


481 CAL 1996


482 CHC 1996


483 CHW 1996


484 CIN 1996


485 CLE 1996


486 COL 1996


487 DET 1996


488 FLA 1996


489 HOU 1996


490 KCR 1996


491 LAD 1996


492 MIL 1996


493 MIN 1996


494 MON 1996


495 NYM 1996


496 NYY 1996


497 OAK 1996


498 PHI 1996


499 PIT 1996


500 SDP 1996


501 SEA 1996


502 SFG 1996


503 STL 1996


504 TEX 1996


505 TOR 1996


506 ATL 1993


507 BAL 1993


508 BOS 1993


509 CAL 1993


510 CHC 1993


511 CHW 1993


512 CIN 1993


513 CLE 1993


514 COL 1993


515 DET 1993


516 FLA 1993


517 HOU 1993


518 KCR 1993


519 LAD 1993


520 MIL 1993


521 MIN 1993


522 MON 1993


523 NYM 1993


524 NYY 1993


525 OAK 1993


526 PHI 1993


527 PIT 1993


528 SDP 1993


529 SEA 1993


530 SFG 1993


531 STL 1993


532 TEX 1993


533 TOR 1993


534 ATL 1992


535 BAL 1992


536 BOS 1992


537 CAL 1992


538 CHC 1992


539 CHW 1992


540 CIN 1992


541 CLE 1992


542 DET 1992


543 HOU 1992


544 KCR 1992


545 LAD 1992


546 MIL 1992


547 MIN 1992


548 MON 1992


549 NYM 1992


550 NYY 1992


551 OAK 1992


552 PHI 1992


553 PIT 1992


554 SDP 1992


555 SEA 1992


556 SFG 1992


557 STL 1992


558 TEX 1992


559 TOR 1992


560 ATL 1991


561 BAL 1991


562 BOS 1991


563 CAL 1991


564 CHC 1991


565 CHW 1991


566 CIN 1991


567 CLE 1991


568 DET 1991


569 HOU 1991


570 KCR 1991


571 LAD 1991


572 MIL 1991


573 MIN 1991


574 MON 1991


575 NYM 1991


576 NYY 1991


577 OAK 1991


578 PHI 1991


579 PIT 1991


580 SDP 1991


581 SEA 1991


582 SFG 1991


583 STL 1991


584 TEX 1991


585 TOR 1991


586 ATL 1990


587 BAL 1990


588 BOS 1990


589 CAL 1990


590 CHC 1990


591 CHW 1990


592 CIN 1990


593 CLE 1990


594 DET 1990


595 HOU 1990


596 KCR 1990


597 LAD 1990


598 MIL 1990


599 MIN 1990


600 MON 1990


601 NYM 1990


602 NYY 1990


603 OAK 1990


604 PHI 1990


605 PIT 1990


606 SDP 1990


607 SEA 1990


608 SFG 1990


609 STL 1990


610 TEX 1990


611 TOR 1990


612 ATL 1989


613 BAL 1989


614 BOS 1989


615 CAL 1989


616 CHC 1989


617 CHW 1989


618 CIN 1989


619 CLE 1989


620 DET 1989


621 HOU 1989


622 KCR 1989


623 LAD 1989


624 MIL 1989


625 MIN 1989


626 MON 1989


627 NYM 1989


628 NYY 1989


629 OAK 1989


630 PHI 1989


631 PIT 1989


632 SDP 1989


633 SEA 1989


634 SFG 1989


635 STL 1989


636 TEX 1989


637 TOR 1989


638 ATL 1988


639 BAL 1988


640 BOS 1988


641 CAL 1988


642 CHC 1988


643 CHW 1988


644 CIN 1988


645 CLE 1988


646 DET 1988


647 HOU 1988


648 KCR 1988


649 LAD 1988


650 MIL 1988


651 MIN 1988


652 MON 1988


653 NYM 1988


654 NYY 1988


655 OAK 1988


656 PHI 1988


657 PIT 1988


658 SDP 1988


659 SEA 1988


660 SFG 1988


661 STL 1988


662 TEX 1988


663 TOR 1988


664 ATL 1987


665 BAL 1987


666 BOS 1987


667 CAL 1987


668 CHC 1987


669 CHW 1987


670 CIN 1987


671 CLE 1987


672 DET 1987


673 HOU 1987


674 KCR 1987


675 LAD 1987


676 MIL 1987


677 MIN 1987


678 MON 1987


679 NYM 1987


680 NYY 1987


681 OAK 1987


682 PHI 1987


683 PIT 1987


684 SDP 1987


685 SEA 1987


686 SFG 1987


687 STL 1987


688 TEX 1987


689 TOR 1987


690 ATL 1986


691 BAL 1986


692 BOS 1986


693 CAL 1986


694 CHC 1986


695 CHW 1986


696 CIN 1986


697 CLE 1986


698 DET 1986


699 HOU 1986


700 KCR 1986


701 LAD 1986


702 MIL 1986


703 MIN 1986


704 MON 1986


705 NYM 1986


706 NYY 1986


707 OAK 1986


708 PHI 1986


709 PIT 1986


710 SDP 1986


711 SEA 1986


712 SFG 1986


713 STL 1986


714 TEX 1986


715 TOR 1986


716 ATL 1985


717 BAL 1985


718 BOS 1985


719 CAL 1985


720 CHC 1985


721 CHW 1985


722 CIN 1985


723 CLE 1985


724 DET 1985


725 HOU 1985


726 KCR 1985


727 LAD 1985


728 MIL 1985


729 MIN 1985


730 MON 1985


731 NYM 1985


732 NYY 1985


733 OAK 1985


734 PHI 1985


735 PIT 1985


736 SDP 1985


737 SEA 1985


738 SFG 1985


739 STL 1985


740 TEX 1985


741 TOR 1985


742 ATL 1984


743 BAL 1984


744 BOS 1984


745 CAL 1984


746 CHC 1984


747 CHW 1984


748 CIN 1984


749 CLE 1984


750 DET 1984


751 HOU 1984


752 KCR 1984


753 LAD 1984


754 MIL 1984


755 MIN 1984


756 MON 1984


757 NYM 1984


758 NYY 1984


759 OAK 1984


760 PHI 1984


761 PIT 1984


762 SDP 1984


763 SEA 1984


764 SFG 1984


765 STL 1984


766 TEX 1984


767 TOR 1984


768 ATL 1983


769 BAL 1983


770 BOS 1983


771 CAL 1983


772 CHC 1983


773 CHW 1983


774 CIN 1983


775 CLE 1983


776 DET 1983


777 HOU 1983


778 KCR 1983


779 LAD 1983


780 MIL 1983


781 MIN 1983


782 MON 1983


783 NYM 1983


784 NYY 1983


785 OAK 1983


786 PHI 1983


787 PIT 1983


788 SDP 1983


789 SEA 1983


790 SFG 1983


791 STL 1983


792 TEX 1983


793 TOR 1983


794 ATL 1982


795 BAL 1982


796 BOS 1982


797 CAL 1982


798 CHC 1982


799 CHW 1982


800 CIN 1982


801 CLE 1982


802 DET 1982


803 HOU 1982


804 KCR 1982


805 LAD 1982


806 MIL 1982


807 MIN 1982


808 MON 1982


809 NYM 1982


810 NYY 1982


811 OAK 1982


812 PHI 1982


813 PIT 1982


814 SDP 1982


815 SEA 1982


816 SFG 1982


817 STL 1982


818 TEX 1982


819 TOR 1982


820 ATL 1980


821 BAL 1980


822 BOS 1980


823 CAL 1980


824 CHC 1980


825 CHW 1980


826 CIN 1980


827 CLE 1980


828 DET 1980


829 HOU 1980


830 KCR 1980


831 LAD 1980


832 MIL 1980


833 MIN 1980


834 MON 1980


835 NYM 1980


836 NYY 1980


837 OAK 1980


838 PHI 1980


839 PIT 1980


840 SDP 1980


841 SEA 1980


842 SFG 1980


843 STL 1980


844 TEX 1980


845 TOR 1980


846 ATL 1979


847 BAL 1979


848 BOS 1979


849 CAL 1979


850 CHC 1979


851 CHW 1979


852 CIN 1979


853 CLE 1979


854 DET 1979


855 HOU 1979


856 KCR 1979


857 LAD 1979


858 MIL 1979


859 MIN 1979


860 MON 1979


861 NYM 1979


862 NYY 1979


863 OAK 1979


864 PHI 1979


865 PIT 1979


866 SDP 1979


867 SEA 1979


868 SFG 1979


869 STL 1979


870 TEX 1979


871 TOR 1979


872 ATL 1978


873 BAL 1978


874 BOS 1978


875 CAL 1978


876 CHC 1978


877 CHW 1978


878 CIN 1978


879 CLE 1978


880 DET 1978


881 HOU 1978


882 KCR 1978


883 LAD 1978


884 MIL 1978


885 MIN 1978


886 MON 1978


887 NYM 1978


888 NYY 1978


889 OAK 1978


890 PHI 1978


891 PIT 1978


892 SDP 1978


893 SEA 1978


894 SFG 1978


895 STL 1978


896 TEX 1978


897 TOR 1978


898 ATL 1977


899 BAL 1977


900 BOS 1977


901 CAL 1977


902 CHC 1977


903 CHW 1977


904 CIN 1977


905 CLE 1977


906 DET 1977


907 HOU 1977


908 KCR 1977


909 LAD 1977


910 MIL 1977


911 MIN 1977


912 MON 1977


913 NYM 1977


914 NYY 1977


915 OAK 1977


916 PHI 1977


917 PIT 1977


918 SDP 1977


919 SEA 1977


920 SFG 1977


921 STL 1977


922 TEX 1977


923 TOR 1977


924 ATL 1976


925 BAL 1976


926 BOS 1976


927 CAL 1976


928 CHC 1976


929 CHW 1976


930 CIN 1976


931 CLE 1976


932 DET 1976


933 HOU 1976


934 KCR 1976


935 LAD 1976


936 MIL 1976


937 MIN 1976


938 MON 1976


939 NYM 1976


940 NYY 1976


941 OAK 1976


942 PHI 1976


943 PIT 1976


944 SDP 1976


945 SFG 1976


946 STL 1976


947 TEX 1976


948 ATL 1975


949 BAL 1975


950 BOS 1975


951 CAL 1975


952 CHC 1975


953 CHW 1975


954 CIN 1975


955 CLE 1975


956 DET 1975


957 HOU 1975


958 KCR 1975


959 LAD 1975


960 MIL 1975


961 MIN 1975


962 MON 1975


963 NYM 1975


964 NYY 1975


965 OAK 1975


966 PHI 1975


967 PIT 1975


968 SDP 1975


969 SFG 1975


970 STL 1975


971 TEX 1975


972 ATL 1974


973 BAL 1974


974 BOS 1974


975 CAL 1974


976 CHC 1974


977 CHW 1974


978 CIN 1974


979 CLE 1974


980 DET 1974


981 HOU 1974


982 KCR 1974


983 LAD 1974


984 MIL 1974


985 MIN 1974


986 MON 1974


987 NYM 1974


988 NYY 1974


989 OAK 1974


990 PHI 1974


991 PIT 1974


992 SDP 1974


993 SFG 1974


994 STL 1974


995 TEX 1974


996 ATL 1973


997 BAL 1973


998 BOS 1973


999 CAL 1973


1000 CHC 1973


1001 CHW 1973


1002 CIN 1973


1003 CLE 1973


1004 DET 1973


1005 HOU 1973


1006 KCR 1973


1007 LAD 1973


1008 MIL 1973


1009 MIN 1973


1010 MON 1973


1011 NYM 1973


1012 NYY 1973


1013 OAK 1973


1014 PHI 1973


1015 PIT 1973


1016 SDP 1973


1017 SFG 1973


1018 STL 1973


1019 TEX 1973


1020 ATL 1971


1021 BAL 1971


1022 BOS 1971


1023 CAL 1971


1024 CHC 1971


1025 CHW 1971


1026 CIN 1971


1027 CLE 1971


1028 DET 1971


1029 HOU 1971


1030 KCR 1971


1031 LAD 1971


1032 MIL 1971


1033 MIN 1971


1034 MON 1971


1035 NYM 1971


1036 NYY 1971


1037 OAK 1971


1038 PHI 1971


1039 PIT 1971


1040 SDP 1971


1041 SFG 1971


1042 STL 1971


1043 WSA 1971


1044 ATL 1970


1045 BAL 1970


1046 BOS 1970


1047 CAL 1970


1048 CHC 1970


1049 CHW 1970


1050 CIN 1970


1051 CLE 1970


1052 DET 1970


1053 HOU 1970


1054 KCR 1970


1055 LAD 1970


1056 MIL 1970


1057 MIN 1970


1058 MON 1970


1059 NYM 1970


1060 NYY 1970


1061 OAK 1970


1062 PHI 1970


1063 PIT 1970


1064 SDP 1970


1065 SFG 1970


1066 STL 1970


1067 WSA 1970


1068 ATL 1969


1069 BAL 1969


1070 BOS 1969


1071 CAL 1969


1072 CHC 1969


1073 CHW 1969


1074 CIN 1969


1075 CLE 1969


1076 DET 1969


1077 HOU 1969


1078 KCR 1969


1079 LAD 1969


1080 MIN 1969


1081 MON 1969


1082 NYM 1969


1083 NYY 1969


1084 OAK 1969


1085 PHI 1969


1086 PIT 1969


1087 SDP 1969


1088 SEP 1969


1089 SFG 1969


1090 STL 1969


1091 WSA 1969


1092 ATL 1968


1093 BAL 1968


1094 BOS 1968


1095 CAL 1968


1096 CHC 1968


1097 CHW 1968


1098 CIN 1968


1099 CLE 1968


1100 DET 1968


1101 HOU 1968


1102 LAD 1968


1103 MIN 1968


1104 NYM 1968


1105 NYY 1968


1106 OAK 1968


1107 PHI 1968


1108 PIT 1968


1109 SFG 1968


1110 STL 1968


1111 WSA 1968


1112 ATL 1967


1113 BAL 1967


1114 BOS 1967


1115 CAL 1967


1116 CHC 1967


1117 CHW 1967


1118 CIN 1967


1119 CLE 1967


1120 DET 1967


1121 HOU 1967


1122 KCA 1967


1123 LAD 1967


1124 MIN 1967


1125 NYM 1967


1126 NYY 1967


1127 PHI 1967


1128 PIT 1967


1129 SFG 1967


1130 STL 1967


1131 WSA 1967


1132 ATL 1966


1133 BAL 1966


1134 BOS 1966


1135 CAL 1966


1136 CHC 1966


1137 CHW 1966


1138 CIN 1966


1139 CLE 1966


1140 DET 1966


1141 HOU 1966


1142 KCA 1966


1143 LAD 1966


1144 MIN 1966


1145 NYM 1966


1146 NYY 1966


1147 PHI 1966


1148 PIT 1966


1149 SFG 1966


1150 STL 1966


1151 WSA 1966


1152 BAL 1965


1153 BOS 1965


1154 CAL 1965


1155 CHC 1965


1156 CHW 1965


1157 CIN 1965


1158 CLE 1965


1159 DET 1965


1160 HOU 1965


1161 KCA 1965


1162 LAD 1965


1163 MIN 1965


1164 MLN 1965


1165 NYM 1965


1166 NYY 1965


1167 PHI 1965


1168 PIT 1965


1169 SFG 1965


1170 STL 1965


1171 WSA 1965


1172 BAL 1964


1173 BOS 1964


1174 CHC 1964


1175 CHW 1964


1176 CIN 1964


1177 CLE 1964


1178 DET 1964


1179 HOU 1964


1180 KCA 1964


1181 LAA 1964


1182 LAD 1964


1183 MIN 1964


1184 MLN 1964


1185 NYM 1964


1186 NYY 1964


1187 PHI 1964


1188 PIT 1964


1189 SFG 1964


1190 STL 1964


1191 WSA 1964


1192 BAL 1963


1193 BOS 1963


1194 CHC 1963


1195 CHW 1963


1196 CIN 1963


1197 CLE 1963


1198 DET 1963


1199 HOU 1963


1200 KCA 1963


1201 LAA 1963


1202 LAD 1963


1203 MIN 1963


1204 MLN 1963


1205 NYM 1963


1206 NYY 1963


1207 PHI 1963


1208 PIT 1963


1209 SFG 1963


1210 STL 1963


1211 WSA 1963


1212 BAL 1962


1213 BOS 1962


1214 CHC 1962


1215 CHW 1962


1216 CIN 1962


1217 CLE 1962


1218 DET 1962


1219 HOU 1962


1220 KCA 1962


1221 LAA 1962


1222 LAD 1962


1223 MIN 1962


1224 MLN 1962


1225 NYM 1962


1226 NYY 1962


1227 PHI 1962


1228 PIT 1962


1229 SFG 1962


1230 STL 1962


1231 WSA 1962

In [36]:
for row in pit_df.itertuples():
    
    i = row.Team
    team = row.League
    year = row.Year
    
    if pit_df.itertuples == 1:
        print(i, team, year)

<b> Conclusión :  </b>

- .itertuples(). Recuerda que tienes que utilizar la sintaxis de puntos para referenciar un atributo en una tupla con nombre.

- Puedes crear una nueva variable utilizando la referencia de punto de una fila (como hiciste al almacenar row.Index como la variable i). O puede utilizar la referencia de punto de la fila directamente para realizar cálculos y comprobaciones. Observe que no tuvo que guardar row.Playoffs en una nueva variable en su sentencia de comprobación (pudo utilizar row.Playoffs directamente en su comprobación).

<b>.apply()  </b>

- Esta función actúa como la función de map() que hemos usado. Toma una función de entrada y la aplica a todo el DataFrame

- Para especificar en donde queremos aplicar .apply(), utilizamos 0 para las columnas y 1 para los renglones. con axis = 1 ó 0

In [46]:
#Ejercicio 

# Obtener la suma de tres columnas utilizando .apply()

stats_total = pit_df[['RS','RA','W']].apply(sum, axis = 0)
print('\n')
print(stats_total)

RS    880981
RA    880981
W      99674
dtype: int64

In [6]:
#Ejercicio 

# Obtener la suma de dos renglones de RS Y RA  utilizando .apply()

stats_total = pit_df[['RS','RA']].apply(sum, axis = 1)
print('\n')
print(stats_total)

0       1422
1       1300
2       1417
3       1540
4       1372
        ...
1227    1464
1228    1332
1229    1568
1230    1438
1231    1315
Length: 1232, dtype: int64

<b> Utilizando funciones lambda. </b>

In [18]:
dict = {     
        2012: {'RS' :697, 'RA':  577, 'W' : 90,  'Playoffs' : 0},
        2011: {'RS' :707, 'RA':  614, 'W' : 91,  'Playoffs' : 1},
        2010 : {'RS' : 802, 'RA':  649, 'W': 96,  'Playoffs' : 1},
        2009 :{'RS' : 803, 'RA': 754, 'W':  84,  'Playoffs' : 0},
        2008 :{'RS' :774, 'RA': 671, 'W':  97,   'Playoffs' : 1}}

In [29]:
dict_df = pd.DataFrame(dict)

df = dict_df.transpose()
df

       RS   RA   W  Playoffs
2012  697  577  90         0
2011  707  614  91         1
2010  802  649  96         1
2009  803  754  84         0
2008  774  671  97         1

In [32]:
# Gather sum of all columns
stat_totals = df.apply(sum, axis=0)
print(stat_totals)

RS          3783
RA          3265
W            458
Playoffs       3
dtype: int64

In [33]:
# Gather total runs scored in all games per year
total_runs_scored = df[['RS', 'RA']].apply(sum, axis=1)
print(total_runs_scored)

2012    1274
2011    1321
2010    1451
2009    1557
2008    1445
dtype: int64

In [25]:
def text_playoffs(num_playoffs):
    if num_playoffs == 1:
        return 'yes'
    else:
        return 'no'

In [28]:
# Convert numeric playoffs to text by applying text_playoffs()
textual_playoffs = df.apply(lambda row: text_playoffs(row['Playoffs']), axis=1)
print(textual_playoffs)

2012     no
2011    yes
2010    yes
2009     no
2008    yes
dtype: object

<b> Conclusión : </b>

- El método .apply() permite aplicar funciones a todas las filas o columnas de un DataFrame especificando un eje.

- Si has estado usando pandas durante algún tiempo, habrás notado que una mejor manera de encontrar estas estadísticas sería usar el método incorporado de pandas .sum().

- Podrías haber utilizado rays_df.sum(axis=0) para obtener las sumas de las columnas y rays_df[['RS', 'RA']].sum(axis=1) para obtener las sumas de las filas.

- También podría haber utilizado .apply() directamente en una serie (o columna) del DataFrame. Por ejemplo, podría utilizar rays_df['Playoffs'].apply(text_playoffs) para convertir la columna 'Playoffs' en texto.

<b> Resuelve un debate con .apply() </b>

- Los Diamondbacks de Arizona se han enterado de tus increíbles habilidades analíticas. 
  Les gustaría que les ayudaras a resolver un debate entre los directivos. Un entrenador afirma que el equipo ha llegado a los playoffs todos los años en los que ha tenido un porcentaje de victorias de 0,50 o superior. Otro mánager dice que esto no es cierto.

In [73]:
# Primero obtengamos el dataframe exclusivamente del equipo 'ARI'
ari_team = pit_df[pit_df['Team'] == 'ARI'] 
dr = ari_team.iloc[:, 0:13]

In [90]:
# Eliminamos tablas que no necesitamos
dr.drop(['SLG','BA', 'RankSeason'	,'RankPlayoffs', 'OBP'], axis = 1)

KeyError: "['SLG' 'BA' 'RankSeason' 'RankPlayoffs' 'OBP'] not found in axis"

In [104]:
# Reordenamos las columnas
d_df = dr[['Team',	'League',	'Year',	'RS',	'RA',	'W',	'G', 'Playoffs']]

In [124]:
# Creamos una nueva columna que sera nuestro  nuevo indice 
d_df['index'] = range(15)
d_df.set_index(['index'], inplace = True)
# Ya tenemos nuestro DataFrame para trabajar 
d_df

      Team League  Year   RS   RA    W    G  Playoffs
index
0      ARI     NL  2012  734  688   81  162         0
1      ARI     NL  2011  731  662   94  162         1
2      ARI     NL  2010  713  836   65  162         0
3      ARI     NL  2009  720  782   70  162         0
4      ARI     NL  2008  720  706   82  162         0
5      ARI     NL  2007  712  732   90  162         1
6      ARI     NL  2006  773  788   76  162         0
7      ARI     NL  2005  696  856   77  162         0
8      ARI     NL  2004  615  899   51  162         0
9      ARI     NL  2003  717  685   84  162         0
10     ARI     NL  2002  819  674   98  162         1
11     ARI     NL  2001  818  677   92  162         1
12     ARI     NL  2000  792  754   85  162         0
13     ARI     NL  1999  908  676  100  162         1
14     ARI     NL  1998  665  812   65  162         0

 <b>Utilicemos la siguiente función y el método .apply() para ver qué mánager tiene razón. </b>

In [128]:
def calc_win_perc(wins, games_played):
    win_perc = wins/ games_played
    return np.round(win_perc,2)

> Crea una Serie pandas llamada win_percs aplicando la función calc_win_perc() a cada fila del DataFrame con una función lambda.

In [130]:
win_percs = d_df.apply(lambda row: calc_win_perc(row['W'], row['G']), axis = 1)
print(win_percs, '\n')

index
0     0.50
1     0.58
2     0.40
3     0.43
4     0.51
5     0.56
6     0.47
7     0.48
8     0.31
9     0.52
10    0.60
11    0.57
12    0.52
13    0.62
14    0.40
dtype: float64

In [132]:
# Agregando una nueva columna con los nuevos calculos
d_df['WP'] = win_percs
d_df

      Team League  Year   RS   RA    W    G  Playoffs    WP
index
0      ARI     NL  2012  734  688   81  162         0  0.50
1      ARI     NL  2011  731  662   94  162         1  0.58
2      ARI     NL  2010  713  836   65  162         0  0.40
3      ARI     NL  2009  720  782   70  162         0  0.43
4      ARI     NL  2008  720  706   82  162         0  0.51
5      ARI     NL  2007  712  732   90  162         1  0.56
6      ARI     NL  2006  773  788   76  162         0  0.47
7      ARI     NL  2005  696  856   77  162         0  0.48
8      ARI     NL  2004  615  899   51  162         0  0.31
9      ARI     NL  2003  717  685   84  162         0  0.52
10     ARI     NL  2002  819  674   98  162         1  0.60
11     ARI     NL  2001  818  677   92  162         1  0.57
12     ARI     NL  2000  792  754   85  162         0  0.52
13     ARI     NL  1999  908  676  100  162         1  0.62
14     ARI     NL  1998  665  812   65  162         0  0.40

In [137]:
# Filtrando los equipos donde el WP  sea mayor que .50

d_final = d_df[d_df['WP'] > .50]
d_final

      Team League  Year   RS   RA    W    G  Playoffs    WP
index
1      ARI     NL  2011  731  662   94  162         1  0.58
4      ARI     NL  2008  720  706   82  162         0  0.51
5      ARI     NL  2007  712  732   90  162         1  0.56
9      ARI     NL  2003  717  685   84  162         0  0.52
10     ARI     NL  2002  819  674   98  162         1  0.60
11     ARI     NL  2001  818  677   92  162         1  0.57
12     ARI     NL  2000  792  754   85  162         0  0.52
13     ARI     NL  1999  908  676  100  162         1  0.62

<b> Conclusiones: </b>
- EL que tiene razón es el gerente que afirmó que el equipo no ha llegado a los playoffs todos los años que ha tenido un porcentaje de victorias de 0,50 o más.

- Lamentablemente, el segundo gestor era correcto. En los años 2012, 2008, 2003 y 2000 los Diamondbacks de Arizona tuvieron un porcentaje de victorias mayor o igual a 0,50, pero aun así no llegaron a los playoffs.


- El uso del método .apply() con una función lambda permite aplicar una función a un DataFrame sin necesidad de escribir un bucle for.

### Recordemos que Pandas esta basado en numpy 

- Teniendo esto en cuenta podemos volvernos mas eficacez en nuestros calculos porque podemos vectorizar nuestros calculos en vez de ir fila por fila, podemos aplicar nuestros calculos a todos los renglones en un solo movimiento. 

<b> Utilizando .values podemos vectorizar todos los datos, haciendo que estos se vuelvan un numpy array </b>

In [141]:
# El problema anterior podemos resolverlo con mayor rapidez haciendo lo siguiente
win_perc_np = calc_win_perc(d_df['W'].values, d_df['G'].values)


d_df['WP_2'] = win_perc_np
d_df

      Team League  Year   RS   RA    W    G  Playoffs    WP  WP_2
index
0      ARI     NL  2012  734  688   81  162         0  0.50  0.50
1      ARI     NL  2011  731  662   94  162         1  0.58  0.58
2      ARI     NL  2010  713  836   65  162         0  0.40  0.40
3      ARI     NL  2009  720  782   70  162         0  0.43  0.43
4      ARI     NL  2008  720  706   82  162         0  0.51  0.51
5      ARI     NL  2007  712  732   90  162         1  0.56  0.56
6      ARI     NL  2006  773  788   76  162         0  0.47  0.47
7      ARI     NL  2005  696  856   77  162         0  0.48  0.48
8      ARI     NL  2004  615  899   51  162         0  0.31  0.31
9      ARI     NL  2003  717  685   84  162         0  0.52  0.52
10     ARI     NL  2002  819  674   98  162         1  0.60  0.60
11     ARI     NL  2001  818  677   92  162         1  0.57  0.57
12     ARI     NL  2000  792  754   85  162         0  0.52  0.52
13     ARI     NL  1999  908  676  100  162         1  0.62  0.62
14     ARI     NL  1998  665  812   65  162         0  0.40  0.40

<b> Conclusión:  </b>

- El uso de las matrices subyacentes de un DataFrame para realizar cálculos puede realmente acelerar su código y produce algunas ganancias significativas de eficiencia. 

- NOTA : ¿Te has dado cuenta de que el enfoque de arrays de NumPy no sólo es más rápido, sino que también utiliza menos líneas de código y es más fácil de leer?

## Comparando todos los metodos.

In [143]:
#metodo .itertupples 
ws = []
for row in d_df.itertuples():
    wins = row.W
    games = row.G
    calc_win_perc(wins, games)
    ws.append(calc_win_perc)

# Metodo .apply
win_percs = d_df.apply(lambda row: calc_win_perc(row['W'], row['G']), axis = 1)

# metodo vectorizando 
win_perc_np = calc_win_perc(d_df['W'].values, d_df['G'].values)

<b> Conclusiones finales: </b>

-  Has practicado utilizando tres enfoques diferentes para iterar sobre un DataFrame de pandas y realizar cálculos. ¿Te has dado cuenta de que la aproximación .itertuples() supera a la aproximación .apply()? Aunque ambas implementaciones pueden ser útiles, deberías usar por defecto los arrays subyacentes de un DataFrame para realizar los cálculos.

- Eche un vistazo a sus predicciones de porcentaje de victorias (columna 'WP_preds') y compárelas con los porcentajes de victorias reales (columna 'WP'). No está mal.


- ¡Has hecho un gran trabajo durante todo el curso! ¡Ahora, estás bien encaminado para escribir código Python y pandas eficiente!